//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Organizational Level Requirement Data
 * 
 * &lt;p&gt;Java class for AD_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AD_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dlyinmet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="dlyinmmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element name="msprcmet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="msprcmmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element name="prdinmet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="prdinmmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element name="popinmet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="popinmmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element name="propimet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="propimmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element name="trnaimet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="trnaimmh" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_man_hours_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AD_Type", propOrder = {
    "dlyinmet",
    "dlyinmmh",
    "msprcmet",
    "msprcmmh",
    "prdinmet",
    "prdinmmh",
    "popinmet",
    "popinmmh",
    "propimet",
    "propimmh",
    "trnaimet",
    "trnaimmh",
    "extension"
})
public class ADType {

    /**
     * Daily Inspection Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal dlyinmet;
    /**
     * Daily Inspection Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal dlyinmmh;
    /**
     * Mission Profile Change Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal msprcmet;
    /**
     * Mission Profile Change Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal msprcmmh;
    /**
     * Periodic Inspection Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal prdinmet;
    /**
     * Periodic Inspection Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal prdinmmh;
    /**
     * Postoperative Inspection Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal popinmet;
    /**
     * Postoperative Inspection Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal popinmmh;
    /**
     * Preoperative Inspection Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal propimet;
    /**
     * Preoperative Inspection Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal propimmh;
    /**
     * Turnaround Inspection Mean Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal trnaimet;
    /**
     * Turnaround Inspection Mean Man Hours
     * 
     */
    @XmlElement()
    protected BigDecimal trnaimmh;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Daily Inspection Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDlyinmet() {
        return dlyinmet;
    }

    /**
     * Sets the value of the dlyinmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getDlyinmet()
     */
    public void setDlyinmet(BigDecimal value) {
        this.dlyinmet = value;
    }

    /**
     * Daily Inspection Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDlyinmmh() {
        return dlyinmmh;
    }

    /**
     * Sets the value of the dlyinmmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getDlyinmmh()
     */
    public void setDlyinmmh(BigDecimal value) {
        this.dlyinmmh = value;
    }

    /**
     * Mission Profile Change Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMsprcmet() {
        return msprcmet;
    }

    /**
     * Sets the value of the msprcmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMsprcmet()
     */
    public void setMsprcmet(BigDecimal value) {
        this.msprcmet = value;
    }

    /**
     * Mission Profile Change Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMsprcmmh() {
        return msprcmmh;
    }

    /**
     * Sets the value of the msprcmmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMsprcmmh()
     */
    public void setMsprcmmh(BigDecimal value) {
        this.msprcmmh = value;
    }

    /**
     * Periodic Inspection Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrdinmet() {
        return prdinmet;
    }

    /**
     * Sets the value of the prdinmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPrdinmet()
     */
    public void setPrdinmet(BigDecimal value) {
        this.prdinmet = value;
    }

    /**
     * Periodic Inspection Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrdinmmh() {
        return prdinmmh;
    }

    /**
     * Sets the value of the prdinmmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPrdinmmh()
     */
    public void setPrdinmmh(BigDecimal value) {
        this.prdinmmh = value;
    }

    /**
     * Postoperative Inspection Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPopinmet() {
        return popinmet;
    }

    /**
     * Sets the value of the popinmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPopinmet()
     */
    public void setPopinmet(BigDecimal value) {
        this.popinmet = value;
    }

    /**
     * Postoperative Inspection Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPopinmmh() {
        return popinmmh;
    }

    /**
     * Sets the value of the popinmmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPopinmmh()
     */
    public void setPopinmmh(BigDecimal value) {
        this.popinmmh = value;
    }

    /**
     * Preoperative Inspection Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPropimet() {
        return propimet;
    }

    /**
     * Sets the value of the propimet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPropimet()
     */
    public void setPropimet(BigDecimal value) {
        this.propimet = value;
    }

    /**
     * Preoperative Inspection Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPropimmh() {
        return propimmh;
    }

    /**
     * Sets the value of the propimmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPropimmh()
     */
    public void setPropimmh(BigDecimal value) {
        this.propimmh = value;
    }

    /**
     * Turnaround Inspection Mean Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrnaimet() {
        return trnaimet;
    }

    /**
     * Sets the value of the trnaimet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTrnaimet()
     */
    public void setTrnaimet(BigDecimal value) {
        this.trnaimet = value;
    }

    /**
     * Turnaround Inspection Mean Man Hours
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrnaimmh() {
        return trnaimmh;
    }

    /**
     * Sets the value of the trnaimmh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTrnaimmh()
     */
    public void setTrnaimmh(BigDecimal value) {
        this.trnaimmh = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
