//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Modeling Data
 * 
 * &lt;p&gt;Java class for AI_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AI_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="laborrat" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}labor_rate_Type" minOccurs="0"/&gt;
 *         &lt;element name="lbrrtcrc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}currency_code_Type" minOccurs="0"/&gt;
 *         &lt;element name="nooshops" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}number_of_shops_Type" minOccurs="0"/&gt;
 *         &lt;element name="rprwrksp" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_work_space_cost_Type" minOccurs="0"/&gt;
 *         &lt;element name="rpwksccc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}currency_code_Type" minOccurs="0"/&gt;
 *         &lt;element name="reqdos" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}required_days_of_stock_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attribute name="mdomlvlc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operations_and_maintenance_level_code_Type" /&gt;
 *       &lt;attribute name="mdsrvdsc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}service_designator_code_Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AI_Type", propOrder = {
    "laborrat",
    "lbrrtcrc",
    "nooshops",
    "rprwrksp",
    "rpwksccc",
    "reqdos",
    "extension"
})
public class AIType {

    /**
     * Labor Rate
     * 
     */
    @XmlElement()
    protected BigDecimal laborrat;
    /**
     * Labor Rate Currency Code
     * 
     */
    @XmlElement()
    protected String lbrrtcrc;
    /**
     * Number Of Shops
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer nooshops;
    /**
     * Repair Work Space Cost
     * 
     */
    @XmlElement()
    protected BigDecimal rprwrksp;
    /**
     * Repair Work Space Cost Currency Code
     * 
     */
    @XmlElement()
    protected String rpwksccc;
    /**
     * Required Days Of Stock
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer reqdos;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Modeling Operations And Maintenance Level Code
     * 
     */
    @XmlAttribute(name = "mdomlvlc", required = true)
    protected String mdomlvlc;
    /**
     * Modeling Service Designator Code
     * 
     */
    @XmlAttribute(name = "mdsrvdsc", required = true)
    protected ServiceDesignatorCodeType mdsrvdsc;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Labor Rate
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLaborrat() {
        return laborrat;
    }

    /**
     * Sets the value of the laborrat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getLaborrat()
     */
    public void setLaborrat(BigDecimal value) {
        this.laborrat = value;
    }

    /**
     * Labor Rate Currency Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLbrrtcrc() {
        return lbrrtcrc;
    }

    /**
     * Sets the value of the lbrrtcrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLbrrtcrc()
     */
    public void setLbrrtcrc(String value) {
        this.lbrrtcrc = value;
    }

    /**
     * Number Of Shops
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNooshops() {
        return nooshops;
    }

    /**
     * Sets the value of the nooshops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getNooshops()
     */
    public void setNooshops(Integer value) {
        this.nooshops = value;
    }

    /**
     * Repair Work Space Cost
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRprwrksp() {
        return rprwrksp;
    }

    /**
     * Sets the value of the rprwrksp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getRprwrksp()
     */
    public void setRprwrksp(BigDecimal value) {
        this.rprwrksp = value;
    }

    /**
     * Repair Work Space Cost Currency Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpwksccc() {
        return rpwksccc;
    }

    /**
     * Sets the value of the rpwksccc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRpwksccc()
     */
    public void setRpwksccc(String value) {
        this.rpwksccc = value;
    }

    /**
     * Required Days Of Stock
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReqdos() {
        return reqdos;
    }

    /**
     * Sets the value of the reqdos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getReqdos()
     */
    public void setReqdos(Integer value) {
        this.reqdos = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Modeling Operations And Maintenance Level Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdomlvlc() {
        return mdomlvlc;
    }

    /**
     * Sets the value of the mdomlvlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMdomlvlc()
     */
    public void setMdomlvlc(String value) {
        this.mdomlvlc = value;
    }

    /**
     * Modeling Service Designator Code
     * 
     * @return
     *     possible object is
     *     {@link ServiceDesignatorCodeType }
     *     
     */
    public ServiceDesignatorCodeType getMdsrvdsc() {
        return mdsrvdsc;
    }

    /**
     * Sets the value of the mdsrvdsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDesignatorCodeType }
     *     
     * @see #getMdsrvdsc()
     */
    public void setMdsrvdsc(ServiceDesignatorCodeType value) {
        this.mdsrvdsc = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
