//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Operations and Maintenance Shipping Requirements Data
 * 
 * &lt;p&gt;Java class for AJ_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AJ_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shipdist" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}ship_distance_Type" minOccurs="0"/&gt;
 *         &lt;element name="spdstum" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_of_measure_Type" minOccurs="0"/&gt;
 *         &lt;element name="shiptime" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}ship_time_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attribute name="omlevlfr" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operations_and_maintenance_level_code_Type" /&gt;
 *       &lt;attribute name="omlevlto" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operations_and_maintenance_level_code_Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AJ_Type", propOrder = {
    "shipdist",
    "spdstum",
    "shiptime",
    "extension"
})
public class AJType {

    /**
     * Ship Distance
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer shipdist;
    /**
     * Ship Distance Unit Of Measure
     * 
     */
    protected String spdstum;
    /**
     * Ship Time
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer shiptime;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Operations And Maintenance Level From
     * 
     */
    @XmlAttribute(name = "omlevlfr", required = true)
    protected String omlevlfr;
    /**
     * Operations And Maintenance Level To
     * 
     */
    @XmlAttribute(name = "omlevlto", required = true)
    protected String omlevlto;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Ship Distance
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getShipdist() {
        return shipdist;
    }

    /**
     * Sets the value of the shipdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getShipdist()
     */
    public void setShipdist(Integer value) {
        this.shipdist = value;
    }

    /**
     * Ship Distance Unit Of Measure
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpdstum() {
        return spdstum;
    }

    /**
     * Sets the value of the spdstum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSpdstum()
     */
    public void setSpdstum(String value) {
        this.spdstum = value;
    }

    /**
     * Ship Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getShiptime() {
        return shiptime;
    }

    /**
     * Sets the value of the shiptime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getShiptime()
     */
    public void setShiptime(Integer value) {
        this.shiptime = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Operations And Maintenance Level From
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmlevlfr() {
        return omlevlfr;
    }

    /**
     * Sets the value of the omlevlfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOmlevlfr()
     */
    public void setOmlevlfr(String value) {
        this.omlevlfr = value;
    }

    /**
     * Operations And Maintenance Level To
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmlevlto() {
        return omlevlto;
    }

    /**
     * Sets the value of the omlevlto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOmlevlto()
     */
    public void setOmlevlto(String value) {
        this.omlevlto = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
