//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Failure Mode and Reliability Centered Maintenance Analysis Data
 * 
 * &lt;p&gt;Java class for BF_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="BF_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="efmmtbf" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}engineering_failure_mode_mean_time_between_failure_Type" minOccurs="0"/&gt;
 *         &lt;element name="efmtbfmb" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}measurement_base_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmclass" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}failure_mode_classification_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmratio" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}failure_mode_ratio_Type" minOccurs="0"/&gt;
 *         &lt;element name="fcausen" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fdmeeen" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fdmeln" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fdmenhn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fdmgmn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmdetmn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmpredn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmredrn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="fmremrkn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="rcmconn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="rcmageen" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="rcmrsngn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element name="rcmredrn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="BFA" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}BFA_Type" minOccurs="0"/&gt;
 *         &lt;element name="BH" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}BH_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="BI" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}BI_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attribute name="fmindctr" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}failure_mode_indicator_Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BF_Type", propOrder = {
    "efmmtbf",
    "efmtbfmb",
    "fmclass",
    "fmratio",
    "fcausen",
    "fdmeeen",
    "fdmeln",
    "fdmenhn",
    "fdmgmn",
    "fmdetmn",
    "fmpredn",
    "fmredrn",
    "fmremrkn",
    "rcmconn",
    "rcmageen",
    "rcmrsngn",
    "rcmredrn",
    "extension",
    "bfa",
    "bh",
    "bi"
})
public class BFType {

    /**
     * Engineering Failure Mode Mean Time Between Failure
     * 
     */
    @XmlElement()
    protected BigDecimal efmmtbf;
    /**
     * Engineering Failure Mode Mean Time Between Failure Measurement Base
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "string")
    protected MeasurementBaseType efmtbfmb;
    /**
     * Failure Mode Classification
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "string")
    protected FailureModeClassificationType fmclass;
    /**
     * Failure Mode Ratio
     * 
     */
    @XmlElement()
    protected BigDecimal fmratio;
    /**
     * Failure Cause Narrative
     * 
     */
    @XmlElement()
    protected String fcausen;
    /**
     * Failure Damage Mode Effect End Effect Narrative
     * 
     */
    @XmlElement()
    protected String fdmeeen;
    /**
     * Failure Damage Mode Effect Local Narrative
     * 
     */
    @XmlElement()
    protected String fdmeln;
    /**
     * Failure Damage Mode Effect Next Higher Narrative
     * 
     */
    @XmlElement()
    protected String fdmenhn;
    /**
     * Failure Damage Mode Narrative
     * 
     */
    @XmlElement()
    protected String fdmgmn;
    /**
     * Failure Mode Detection Method Narrative
     * 
     */
    @XmlElement()
    protected String fmdetmn;
    /**
     * Failure Mode Predictability Narrative
     * 
     */
    @XmlElement()
    protected String fmpredn;
    /**
     * Failure Mode Redesign Recommendations Narrative
     * 
     */
    @XmlElement()
    protected String fmredrn;
    /**
     * Failure Mode Remarks Narrative
     * 
     */
    @XmlElement()
    protected String fmremrkn;
    /**
     * Reliability Centered Maintenance Conclusion Narrative
     * 
     */
    protected String rcmconn;
    /**
     * Rcm Age Exploration Narrative
     * 
     */
    @XmlElement()
    protected String rcmageen;
    /**
     * Rcm Reasoning Narrative
     * 
     */
    @XmlElement()
    protected String rcmrsngn;
    /**
     * Rcm Redesign Recommendation Narrative
     * 
     */
    @XmlElement()
    protected String rcmredrn;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Reliability Centered Maintenance Logic Analysis Data
     * 
     */
    @XmlElement(name = "BFA")
    protected BFAType bfa;
    /**
     * Failure Mode Task Data
     * 
     */
    @XmlElement(name = "BH")
    protected List<BHType> bh;
    /**
     * Failure Mode Indicator Mission Phase Code Characteristics Data
     * 
     */
    @XmlElement(name = "BI")
    protected List<BIType> bi;
    /**
     * Failure Mode Indicator
     * 
     */
    @XmlAttribute(name = "fmindctr", required = true)
    protected String fmindctr;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Engineering Failure Mode Mean Time Between Failure
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEfmmtbf() {
        return efmmtbf;
    }

    /**
     * Sets the value of the efmmtbf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getEfmmtbf()
     */
    public void setEfmmtbf(BigDecimal value) {
        this.efmmtbf = value;
    }

    /**
     * Engineering Failure Mode Mean Time Between Failure Measurement Base
     * 
     * @return
     *     possible object is
     *     {@link MeasurementBaseType }
     *     
     */
    public MeasurementBaseType getEfmtbfmb() {
        return efmtbfmb;
    }

    /**
     * Sets the value of the efmtbfmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementBaseType }
     *     
     * @see #getEfmtbfmb()
     */
    public void setEfmtbfmb(MeasurementBaseType value) {
        this.efmtbfmb = value;
    }

    /**
     * Failure Mode Classification
     * 
     * @return
     *     possible object is
     *     {@link FailureModeClassificationType }
     *     
     */
    public FailureModeClassificationType getFmclass() {
        return fmclass;
    }

    /**
     * Sets the value of the fmclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailureModeClassificationType }
     *     
     * @see #getFmclass()
     */
    public void setFmclass(FailureModeClassificationType value) {
        this.fmclass = value;
    }

    /**
     * Failure Mode Ratio
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFmratio() {
        return fmratio;
    }

    /**
     * Sets the value of the fmratio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getFmratio()
     */
    public void setFmratio(BigDecimal value) {
        this.fmratio = value;
    }

    /**
     * Failure Cause Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFcausen() {
        return fcausen;
    }

    /**
     * Sets the value of the fcausen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFcausen()
     */
    public void setFcausen(String value) {
        this.fcausen = value;
    }

    /**
     * Failure Damage Mode Effect End Effect Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdmeeen() {
        return fdmeeen;
    }

    /**
     * Sets the value of the fdmeeen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFdmeeen()
     */
    public void setFdmeeen(String value) {
        this.fdmeeen = value;
    }

    /**
     * Failure Damage Mode Effect Local Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdmeln() {
        return fdmeln;
    }

    /**
     * Sets the value of the fdmeln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFdmeln()
     */
    public void setFdmeln(String value) {
        this.fdmeln = value;
    }

    /**
     * Failure Damage Mode Effect Next Higher Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdmenhn() {
        return fdmenhn;
    }

    /**
     * Sets the value of the fdmenhn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFdmenhn()
     */
    public void setFdmenhn(String value) {
        this.fdmenhn = value;
    }

    /**
     * Failure Damage Mode Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdmgmn() {
        return fdmgmn;
    }

    /**
     * Sets the value of the fdmgmn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFdmgmn()
     */
    public void setFdmgmn(String value) {
        this.fdmgmn = value;
    }

    /**
     * Failure Mode Detection Method Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmdetmn() {
        return fmdetmn;
    }

    /**
     * Sets the value of the fmdetmn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFmdetmn()
     */
    public void setFmdetmn(String value) {
        this.fmdetmn = value;
    }

    /**
     * Failure Mode Predictability Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmpredn() {
        return fmpredn;
    }

    /**
     * Sets the value of the fmpredn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFmpredn()
     */
    public void setFmpredn(String value) {
        this.fmpredn = value;
    }

    /**
     * Failure Mode Redesign Recommendations Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmredrn() {
        return fmredrn;
    }

    /**
     * Sets the value of the fmredrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFmredrn()
     */
    public void setFmredrn(String value) {
        this.fmredrn = value;
    }

    /**
     * Failure Mode Remarks Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmremrkn() {
        return fmremrkn;
    }

    /**
     * Sets the value of the fmremrkn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFmremrkn()
     */
    public void setFmremrkn(String value) {
        this.fmremrkn = value;
    }

    /**
     * Reliability Centered Maintenance Conclusion Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmconn() {
        return rcmconn;
    }

    /**
     * Sets the value of the rcmconn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmconn()
     */
    public void setRcmconn(String value) {
        this.rcmconn = value;
    }

    /**
     * Rcm Age Exploration Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmageen() {
        return rcmageen;
    }

    /**
     * Sets the value of the rcmageen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmageen()
     */
    public void setRcmageen(String value) {
        this.rcmageen = value;
    }

    /**
     * Rcm Reasoning Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmrsngn() {
        return rcmrsngn;
    }

    /**
     * Sets the value of the rcmrsngn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmrsngn()
     */
    public void setRcmrsngn(String value) {
        this.rcmrsngn = value;
    }

    /**
     * Rcm Redesign Recommendation Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmredrn() {
        return rcmredrn;
    }

    /**
     * Sets the value of the rcmredrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmredrn()
     */
    public void setRcmredrn(String value) {
        this.rcmredrn = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Reliability Centered Maintenance Logic Analysis Data
     * 
     * @return
     *     possible object is
     *     {@link BFAType }
     *     
     */
    public BFAType getBFA() {
        return bfa;
    }

    /**
     * Sets the value of the bfa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BFAType }
     *     
     * @see #getBFA()
     */
    public void setBFA(BFAType value) {
        this.bfa = value;
    }

    /**
     * Failure Mode Task Data
     * 
     * Gets the value of the bh property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the bh property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BHType }
     * </p>
     * 
     * 
     * @return
     *     The value of the bh property.
     */
    public List<BHType> getBH() {
        if (bh == null) {
            bh = new ArrayList<>();
        }
        return this.bh;
    }

    /**
     * Failure Mode Indicator Mission Phase Code Characteristics Data
     * 
     * Gets the value of the bi property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the bi property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BIType }
     * </p>
     * 
     * 
     * @return
     *     The value of the bi property.
     */
    public List<BIType> getBI() {
        if (bi == null) {
            bi = new ArrayList<>();
        }
        return this.bi;
    }

    /**
     * Failure Mode Indicator
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmindctr() {
        return fmindctr;
    }

    /**
     * Sets the value of the fmindctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFmindctr()
     */
    public void setFmindctr(String value) {
        this.fmindctr = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
