//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Subtask Requirement Narrative Data
 * 
 * &lt;p&gt;Java class for CB_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="CB_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="elind" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}element_indicator_Type" minOccurs="0"/&gt;
 *         &lt;element name="subtdesc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}subtask_description_Type" minOccurs="0"/&gt;
 *         &lt;element name="subtaid" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}task_identification_Type" minOccurs="0"/&gt;
 *         &lt;element name="subtmmet" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_minute_elapsed_time_Type" minOccurs="0"/&gt;
 *         &lt;element name="subtwaca" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}work_area_code_access_Type" minOccurs="0"/&gt;
 *         &lt;element name="subtwacz" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}work_area_code_zone_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CD" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CD_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CL" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CL_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CM" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CM_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CQ" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CQ_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CR" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CR_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CS" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CS_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CT" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CT_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CUU" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CUU_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attribute name="subtano" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}subtask_number_Type" /&gt;
 *       &lt;attribute name="CB_ref" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CB_Type", propOrder = {
    "elind",
    "subtdesc",
    "subtaid",
    "subtmmet",
    "subtwaca",
    "subtwacz",
    "extension",
    "cd",
    "cl",
    "cm",
    "cq",
    "cr",
    "cs",
    "ct",
    "cuu"
})
public class CBType {

    /**
     * Element Indicator
     * 
     */
    @XmlElement()
    protected Boolean elind;
    /**
     * Subtask Description
     * 
     */
    @XmlElement()
    protected String subtdesc;
    /**
     * Subtask Identification
     * 
     */
    @XmlElement()
    protected String subtaid;
    /**
     * Subtask Mean Minute Elapsed Time
     * 
     */
    @XmlElement()
    protected BigDecimal subtmmet;
    /**
     * Subtask Work Area Code Access
     * 
     */
    @XmlElement()
    protected String subtwaca;
    /**
     * Subtask Work Area Code Zone
     * 
     */
    @XmlElement()
    protected String subtwacz;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Subtask Personnel Requirement Data
     * 
     */
    @XmlElement(name = "CD")
    protected List<CDType> cd;
    /**
     * Task Subtask Associated Narrative Data
     * 
     */
    @XmlElement(name = "CL")
    protected List<CLType> cl;
    /**
     * Electronic Documentation Data
     * 
     */
    @XmlElement(name = "CM")
    protected List<CMType> cm;
    /**
     * Subtask Digital File Data
     * 
     */
    @XmlElement(name = "CQ")
    protected List<CQType> cq;
    /**
     * Subtask Support Equipment Data
     * 
     */
    @XmlElement(name = "CR")
    protected List<CRType> cr;
    /**
     * Subtask Provisioned Item Data
     * 
     */
    @XmlElement(name = "CS")
    protected List<CSType> cs;
    /**
     * Subtask Objective States Data
     * 
     */
    @XmlElement(name = "CT")
    protected List<CTType> ct;
    /**
     * Subtask Circuit Breaker Objective States By Group Data
     * 
     */
    @XmlElement(name = "CUU")
    protected List<CUUType> cuu;
    /**
     * Subtask Number
     * 
     */
    @XmlAttribute(name = "subtano", required = true)
    protected int subtano;
    @XmlAttribute(name = "CB_ref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object cbRef;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Element Indicator
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getElind() {
        return elind;
    }

    /**
     * Sets the value of the elind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getElind()
     */
    public void setElind(Boolean value) {
        this.elind = value;
    }

    /**
     * Subtask Description
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtdesc() {
        return subtdesc;
    }

    /**
     * Sets the value of the subtdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtdesc()
     */
    public void setSubtdesc(String value) {
        this.subtdesc = value;
    }

    /**
     * Subtask Identification
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtaid() {
        return subtaid;
    }

    /**
     * Sets the value of the subtaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtaid()
     */
    public void setSubtaid(String value) {
        this.subtaid = value;
    }

    /**
     * Subtask Mean Minute Elapsed Time
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubtmmet() {
        return subtmmet;
    }

    /**
     * Sets the value of the subtmmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getSubtmmet()
     */
    public void setSubtmmet(BigDecimal value) {
        this.subtmmet = value;
    }

    /**
     * Subtask Work Area Code Access
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtwaca() {
        return subtwaca;
    }

    /**
     * Sets the value of the subtwaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtwaca()
     */
    public void setSubtwaca(String value) {
        this.subtwaca = value;
    }

    /**
     * Subtask Work Area Code Zone
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtwacz() {
        return subtwacz;
    }

    /**
     * Sets the value of the subtwacz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtwacz()
     */
    public void setSubtwacz(String value) {
        this.subtwacz = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Subtask Personnel Requirement Data
     * 
     * Gets the value of the cd property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cd property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cd property.
     */
    public List<CDType> getCD() {
        if (cd == null) {
            cd = new ArrayList<>();
        }
        return this.cd;
    }

    /**
     * Task Subtask Associated Narrative Data
     * 
     * Gets the value of the cl property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cl property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cl property.
     */
    public List<CLType> getCL() {
        if (cl == null) {
            cl = new ArrayList<>();
        }
        return this.cl;
    }

    /**
     * Electronic Documentation Data
     * 
     * Gets the value of the cm property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cm property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CMType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cm property.
     */
    public List<CMType> getCM() {
        if (cm == null) {
            cm = new ArrayList<>();
        }
        return this.cm;
    }

    /**
     * Subtask Digital File Data
     * 
     * Gets the value of the cq property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cq property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CQType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cq property.
     */
    public List<CQType> getCQ() {
        if (cq == null) {
            cq = new ArrayList<>();
        }
        return this.cq;
    }

    /**
     * Subtask Support Equipment Data
     * 
     * Gets the value of the cr property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cr property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CRType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cr property.
     */
    public List<CRType> getCR() {
        if (cr == null) {
            cr = new ArrayList<>();
        }
        return this.cr;
    }

    /**
     * Subtask Provisioned Item Data
     * 
     * Gets the value of the cs property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cs property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CSType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cs property.
     */
    public List<CSType> getCS() {
        if (cs == null) {
            cs = new ArrayList<>();
        }
        return this.cs;
    }

    /**
     * Subtask Objective States Data
     * 
     * Gets the value of the ct property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ct property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTType }
     * </p>
     * 
     * 
     * @return
     *     The value of the ct property.
     */
    public List<CTType> getCT() {
        if (ct == null) {
            ct = new ArrayList<>();
        }
        return this.ct;
    }

    /**
     * Subtask Circuit Breaker Objective States By Group Data
     * 
     * Gets the value of the cuu property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cuu property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCUU().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUUType }
     * </p>
     * 
     * 
     * @return
     *     The value of the cuu property.
     */
    public List<CUUType> getCUU() {
        if (cuu == null) {
            cuu = new ArrayList<>();
        }
        return this.cuu;
    }

    /**
     * Subtask Number
     * 
     */
    public int getSubtano() {
        return subtano;
    }

    /**
     * Sets the value of the subtano property.
     * 
     */
    public void setSubtano(int value) {
        this.subtano = value;
    }

    /**
     * Gets the value of the cbRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCBRef() {
        return cbRef;
    }

    /**
     * Sets the value of the cbRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCBRef(Object value) {
        this.cbRef = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
