//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for circuit_breaker_type_Type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="circuit_breaker_type_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="electronic_circuit_breaker"/&gt;
 *     &lt;enumeration value="electromechanical_circuit_breaker"/&gt;
 *     &lt;enumeration value="dummy_circuit_breaker"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "circuit_breaker_type_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum CircuitBreakerTypeType {

    @XmlEnumValue("electronic_circuit_breaker")
    ELECTRONIC_CIRCUIT_BREAKER("electronic_circuit_breaker"),
    @XmlEnumValue("electromechanical_circuit_breaker")
    ELECTROMECHANICAL_CIRCUIT_BREAKER("electromechanical_circuit_breaker"),
    @XmlEnumValue("dummy_circuit_breaker")
    DUMMY_CIRCUIT_BREAKER("dummy_circuit_breaker");
    private final String value;

    CircuitBreakerTypeType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static CircuitBreakerTypeType fromValue(String v) {
        for (CircuitBreakerTypeType c: CircuitBreakerTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
