//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Support Equipment Authorization Data
 * 
 * &lt;p&gt;Java class for ED_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ED_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numbactv" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}number_of_activities_Type" minOccurs="0"/&gt;
 *         &lt;element name="seqtpact" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_activity_Type" minOccurs="0"/&gt;
 *         &lt;element name="typeactv" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}type_of_activity_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attribute name="actnmloc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}activity_name_location_Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED_Type", propOrder = {
    "numbactv",
    "seqtpact",
    "typeactv",
    "extension"
})
public class EDType {

    /**
     * Number Of Activities
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer numbactv;
    /**
     * Support Equipment Quantity Per Activity
     * 
     */
    @XmlElement()
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer seqtpact;
    /**
     * Type Of Activity
     * 
     */
    @XmlElement()
    protected String typeactv;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Activity Name Location
     * 
     */
    @XmlAttribute(name = "actnmloc", required = true)
    protected String actnmloc;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Number Of Activities
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumbactv() {
        return numbactv;
    }

    /**
     * Sets the value of the numbactv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getNumbactv()
     */
    public void setNumbactv(Integer value) {
        this.numbactv = value;
    }

    /**
     * Support Equipment Quantity Per Activity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqtpact() {
        return seqtpact;
    }

    /**
     * Sets the value of the seqtpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSeqtpact()
     */
    public void setSeqtpact(Integer value) {
        this.seqtpact = value;
    }

    /**
     * Type Of Activity
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeactv() {
        return typeactv;
    }

    /**
     * Sets the value of the typeactv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTypeactv()
     */
    public void setTypeactv(String value) {
        this.typeactv = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Activity Name Location
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActnmloc() {
        return actnmloc;
    }

    /**
     * Sets the value of the actnmloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getActnmloc()
     */
    public void setActnmloc(String value) {
        this.actnmloc = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
