//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for reason_for_supersedure_deletion_Type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="reason_for_supersedure_deletion_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A1"/&gt;
 *     &lt;enumeration value="B1"/&gt;
 *     &lt;enumeration value="B2"/&gt;
 *     &lt;enumeration value="B3"/&gt;
 *     &lt;enumeration value="B4"/&gt;
 *     &lt;enumeration value="B5"/&gt;
 *     &lt;enumeration value="B6"/&gt;
 *     &lt;enumeration value="B7"/&gt;
 *     &lt;enumeration value="C1"/&gt;
 *     &lt;enumeration value="D1"/&gt;
 *     &lt;enumeration value="F1"/&gt;
 *     &lt;enumeration value="F2"/&gt;
 *     &lt;enumeration value="F3"/&gt;
 *     &lt;enumeration value="G1"/&gt;
 *     &lt;enumeration value="H1"/&gt;
 *     &lt;enumeration value="I1"/&gt;
 *     &lt;enumeration value="J1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "reason_for_supersedure_deletion_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum ReasonForSupersedureDeletionType {

    @XmlEnumValue("A1")
    A_1("A1"),
    @XmlEnumValue("B1")
    B_1("B1"),
    @XmlEnumValue("B2")
    B_2("B2"),
    @XmlEnumValue("B3")
    B_3("B3"),
    @XmlEnumValue("B4")
    B_4("B4"),
    @XmlEnumValue("B5")
    B_5("B5"),
    @XmlEnumValue("B6")
    B_6("B6"),
    @XmlEnumValue("B7")
    B_7("B7"),
    @XmlEnumValue("C1")
    C_1("C1"),
    @XmlEnumValue("D1")
    D_1("D1"),
    @XmlEnumValue("F1")
    F_1("F1"),
    @XmlEnumValue("F2")
    F_2("F2"),
    @XmlEnumValue("F3")
    F_3("F3"),
    @XmlEnumValue("G1")
    G_1("G1"),
    @XmlEnumValue("H1")
    H_1("H1"),
    @XmlEnumValue("I1")
    I_1("I1"),
    @XmlEnumValue("J1")
    J_1("J1");
    private final String value;

    ReasonForSupersedureDeletionType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ReasonForSupersedureDeletionType fromValue(String v) {
        for (ReasonForSupersedureDeletionType c: ReasonForSupersedureDeletionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
