//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for recommended_military_rank_rate_Type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="recommended_military_rank_rate_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="C00"/&gt;
 *     &lt;enumeration value="E01"/&gt;
 *     &lt;enumeration value="E02"/&gt;
 *     &lt;enumeration value="E03"/&gt;
 *     &lt;enumeration value="E04"/&gt;
 *     &lt;enumeration value="E05"/&gt;
 *     &lt;enumeration value="E06"/&gt;
 *     &lt;enumeration value="E07"/&gt;
 *     &lt;enumeration value="E08"/&gt;
 *     &lt;enumeration value="E09"/&gt;
 *     &lt;enumeration value="W01"/&gt;
 *     &lt;enumeration value="W02"/&gt;
 *     &lt;enumeration value="W03"/&gt;
 *     &lt;enumeration value="W04"/&gt;
 *     &lt;enumeration value="W05"/&gt;
 *     &lt;enumeration value="O01"/&gt;
 *     &lt;enumeration value="O02"/&gt;
 *     &lt;enumeration value="O03"/&gt;
 *     &lt;enumeration value="O04"/&gt;
 *     &lt;enumeration value="O05"/&gt;
 *     &lt;enumeration value="O06"/&gt;
 *     &lt;enumeration value="O07"/&gt;
 *     &lt;enumeration value="O08"/&gt;
 *     &lt;enumeration value="O09"/&gt;
 *     &lt;enumeration value="O10"/&gt;
 *     &lt;enumeration value="O11"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "recommended_military_rank_rate_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum RecommendedMilitaryRankRateType {

    @XmlEnumValue("C00")
    C_00("C00"),
    @XmlEnumValue("E01")
    E_01("E01"),
    @XmlEnumValue("E02")
    E_02("E02"),
    @XmlEnumValue("E03")
    E_03("E03"),
    @XmlEnumValue("E04")
    E_04("E04"),
    @XmlEnumValue("E05")
    E_05("E05"),
    @XmlEnumValue("E06")
    E_06("E06"),
    @XmlEnumValue("E07")
    E_07("E07"),
    @XmlEnumValue("E08")
    E_08("E08"),
    @XmlEnumValue("E09")
    E_09("E09"),
    @XmlEnumValue("W01")
    W_01("W01"),
    @XmlEnumValue("W02")
    W_02("W02"),
    @XmlEnumValue("W03")
    W_03("W03"),
    @XmlEnumValue("W04")
    W_04("W04"),
    @XmlEnumValue("W05")
    W_05("W05"),
    @XmlEnumValue("O01")
    O_01("O01"),
    @XmlEnumValue("O02")
    O_02("O02"),
    @XmlEnumValue("O03")
    O_03("O03"),
    @XmlEnumValue("O04")
    O_04("O04"),
    @XmlEnumValue("O05")
    O_05("O05"),
    @XmlEnumValue("O06")
    O_06("O06"),
    @XmlEnumValue("O07")
    O_07("O07"),
    @XmlEnumValue("O08")
    O_08("O08"),
    @XmlEnumValue("O09")
    O_09("O09"),
    @XmlEnumValue("O10")
    O_10("O10"),
    @XmlEnumValue("O11")
    O_11("O11");
    private final String value;

    RecommendedMilitaryRankRateType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static RecommendedMilitaryRankRateType fromValue(String v) {
        for (RecommendedMilitaryRankRateType c: RecommendedMilitaryRankRateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
