//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for shipping_configuration_Type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="shipping_configuration_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CB"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="CN"/&gt;
 *     &lt;enumeration value="CR"/&gt;
 *     &lt;enumeration value="CS"/&gt;
 *     &lt;enumeration value="CT"/&gt;
 *     &lt;enumeration value="CU"/&gt;
 *     &lt;enumeration value="CY"/&gt;
 *     &lt;enumeration value="DR"/&gt;
 *     &lt;enumeration value="EC"/&gt;
 *     &lt;enumeration value="ED"/&gt;
 *     &lt;enumeration value="KE"/&gt;
 *     &lt;enumeration value="LS"/&gt;
 *     &lt;enumeration value="MW"/&gt;
 *     &lt;enumeration value="MX"/&gt;
 *     &lt;enumeration value="PT"/&gt;
 *     &lt;enumeration value="EL"/&gt;
 *     &lt;enumeration value="RT"/&gt;
 *     &lt;enumeration value="SB"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="VE"/&gt;
 *     &lt;enumeration value="VO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "shipping_configuration_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum ShippingConfigurationType {

    CB,
    CM,
    CN,
    CR,
    CS,
    CT,
    CU,
    CY,
    DR,
    EC,
    ED,
    KE,
    LS,
    MW,
    MX,
    PT,
    EL,
    RT,
    SB,
    SD,
    VE,
    VO;

    public String value() {
        return name();
    }

    public static ShippingConfigurationType fromValue(String v) {
        return valueOf(v);
    }

}
