//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for task_subtask_associated_narrative_type_Type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="task_subtask_associated_narrative_type_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WARNING"/&gt;
 *     &lt;enumeration value="CAUTION"/&gt;
 *     &lt;enumeration value="NOTE"/&gt;
 *     &lt;enumeration value="SPECIAL REQUIREMENT"/&gt;
 *     &lt;enumeration value="DANGER"/&gt;
 *     &lt;enumeration value="EXAMPLE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "task_subtask_associated_narrative_type_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum TaskSubtaskAssociatedNarrativeTypeType {

    WARNING("WARNING"),
    CAUTION("CAUTION"),
    NOTE("NOTE"),
    @XmlEnumValue("SPECIAL REQUIREMENT")
    SPECIAL_REQUIREMENT("SPECIAL REQUIREMENT"),
    DANGER("DANGER"),
    EXAMPLE("EXAMPLE");
    private final String value;

    TaskSubtaskAssociatedNarrativeTypeType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static TaskSubtaskAssociatedNarrativeTypeType fromValue(String v) {
        for (TaskSubtaskAssociatedNarrativeTypeType c: TaskSubtaskAssociatedNarrativeTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
