//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Article Requiring Support Unit Under Test Data
 * 
 * &lt;p&gt;Java class for UA_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UA_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uutallow" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}allowance_document_number_Type" minOccurs="0"/&gt;
 *         &lt;element name="uutexpln" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_under_test_explanation_data_Type" minOccurs="0"/&gt;
 *         &lt;element name="uutmpno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_plan_number_Type" minOccurs="0"/&gt;
 *         &lt;element name="uuttrdno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}test_requirements_document_number_Type" minOccurs="0"/&gt;
 *         &lt;element name="uutwpref" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_under_test_work_package_reference_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="UB" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}UB_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UA_Type", propOrder = {
    "uutallow",
    "uutexpln",
    "uutmpno",
    "uuttrdno",
    "uutwpref",
    "extension",
    "ub"
})
public class UAType {

    /**
     * Unit Under Test Allowance
     * 
     */
    @XmlElement()
    protected String uutallow;
    /**
     * Unit Under Test Explanation
     * 
     */
    @XmlElement()
    protected String uutexpln;
    /**
     * Unit Under Test Maintenance Plan Number
     * 
     */
    @XmlElement()
    protected String uutmpno;
    /**
     * Unit Under Test Test Requirements Document Number
     * 
     */
    @XmlElement()
    protected String uuttrdno;
    /**
     * Unit Under Test Work Package Reference
     * 
     */
    @XmlElement()
    protected String uutwpref;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Unit Under Test Support Equipment Data
     * 
     */
    @XmlElement(name = "UB")
    protected List<UBType> ub;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Unit Under Test Allowance
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUutallow() {
        return uutallow;
    }

    /**
     * Sets the value of the uutallow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUutallow()
     */
    public void setUutallow(String value) {
        this.uutallow = value;
    }

    /**
     * Unit Under Test Explanation
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUutexpln() {
        return uutexpln;
    }

    /**
     * Sets the value of the uutexpln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUutexpln()
     */
    public void setUutexpln(String value) {
        this.uutexpln = value;
    }

    /**
     * Unit Under Test Maintenance Plan Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUutmpno() {
        return uutmpno;
    }

    /**
     * Sets the value of the uutmpno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUutmpno()
     */
    public void setUutmpno(String value) {
        this.uutmpno = value;
    }

    /**
     * Unit Under Test Test Requirements Document Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuttrdno() {
        return uuttrdno;
    }

    /**
     * Sets the value of the uuttrdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUuttrdno()
     */
    public void setUuttrdno(String value) {
        this.uuttrdno = value;
    }

    /**
     * Unit Under Test Work Package Reference
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUutwpref() {
        return uutwpref;
    }

    /**
     * Sets the value of the uutwpref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUutwpref()
     */
    public void setUutwpref(String value) {
        this.uutwpref = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Unit Under Test Support Equipment Data
     * 
     * Gets the value of the ub property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ub property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getUB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UBType }
     * </p>
     * 
     * 
     * @return
     *     The value of the ub property.
     */
    public List<UBType> getUB() {
        if (ub == null) {
            ub = new ArrayList<>();
        }
        return this.ub;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
