//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.glamdringdefense.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Digital File Data
 * 
 * &lt;p&gt;Java class for XT_Type complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="XT_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="caption" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}caption_Type" minOccurs="0"/&gt;
 *         &lt;element name="docflext" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}document_file_extension_Type" minOccurs="0"/&gt;
 *         &lt;element name="drw" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}drawing_Type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/&gt;
 *       &lt;attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/&gt;
 *       &lt;attribute name="docid" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}document_id_Type" /&gt;
 *       &lt;attribute name="origcode" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}commercial_and_government_entity_code_Type" /&gt;
 *       &lt;attribute name="issueno" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}issue_number_Type" /&gt;
 *       &lt;attribute name="secclass" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}security_classification_Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XT_Type", propOrder = {
    "caption",
    "docflext",
    "drw",
    "extension"
})
@XmlSeeAlso({
    com.glamdringdefense.geia0007c.FileType.Change.XT.class
})
public class XTType {

    /**
     * Caption
     * 
     */
    @XmlElement()
    protected String caption;
    /**
     * Document File Extension
     * 
     */
    @XmlElement()
    protected String docflext;
    /**
     * Drawing
     * 
     */
    @XmlElement()
    protected byte[] drw;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Document Id
     * 
     */
    @XmlAttribute(name = "docid", required = true)
    protected String docid;
    /**
     * Originator Code
     * 
     */
    @XmlAttribute(name = "origcode", required = true)
    protected String origcode;
    /**
     * Issue Number
     * 
     */
    @XmlAttribute(name = "issueno", required = true)
    protected int issueno;
    /**
     * Security Classification
     * 
     */
    @XmlAttribute(name = "secclass", required = true)
    protected int secclass;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Caption
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCaption()
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Document File Extension
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocflext() {
        return docflext;
    }

    /**
     * Sets the value of the docflext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocflext()
     */
    public void setDocflext(String value) {
        this.docflext = value;
    }

    /**
     * Drawing
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDrw() {
        return drw;
    }

    /**
     * Sets the value of the drw property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     * @see #getDrw()
     */
    public void setDrw(byte[] value) {
        this.drw = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Document Id
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocid() {
        return docid;
    }

    /**
     * Sets the value of the docid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocid()
     */
    public void setDocid(String value) {
        this.docid = value;
    }

    /**
     * Originator Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigcode() {
        return origcode;
    }

    /**
     * Sets the value of the origcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOrigcode()
     */
    public void setOrigcode(String value) {
        this.origcode = value;
    }

    /**
     * Issue Number
     * 
     */
    public int getIssueno() {
        return issueno;
    }

    /**
     * Sets the value of the issueno property.
     * 
     */
    public void setIssueno(int value) {
        this.issueno = value;
    }

    /**
     * Security Classification
     * 
     */
    public int getSecclass() {
        return secclass;
    }

    /**
     * Sets the value of the secclass property.
     * 
     */
    public void setSecclass(int value) {
        this.secclass = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
