//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * War Peace Operations and Maintenance Requirement Data
 * 
 * <p>Java class for AB_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AB_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="addreqmt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}additional_requirements_Type" minOccurs="0"/>
 *         <element name="annnomsn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}annual_number_of_missions_Type" minOccurs="0"/>
 *         <element name="annopday" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}annual_operating_days_Type" minOccurs="0"/>
 *         <element name="annoptim" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}annual_operating_time_Type" minOccurs="0"/>
 *         <element name="mmsndur" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}mean_mission_duration_Type" minOccurs="0"/>
 *         <element name="mmsdurmb" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}measurement_base_Type" minOccurs="0"/>
 *         <element name="reqadldt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}administrative_and_logistics_delay_time_Type" minOccurs="0"/>
 *         <element name="reqopav" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operational_availability_Type" minOccurs="0"/>
 *         <element name="reqstbyt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}standby_time_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="AC" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}AC_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="opreqind" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operational_requirement_indicator_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AB_Type", propOrder = {
    "addreqmt",
    "annnomsn",
    "annopday",
    "annoptim",
    "mmsndur",
    "mmsdurmb",
    "reqadldt",
    "reqopav",
    "reqstbyt",
    "extension",
    "ac"
})
public class ABType {

    /**
     * Additional Requirements
     * 
     */
    @XmlElement
    protected String addreqmt;
    /**
     * Annual Number of Missions
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer annnomsn;
    /**
     * Annual Operating Days
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer annopday;
    /**
     * Annual Operating Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer annoptim;
    /**
     * Mean Mission Duration
     * 
     */
    @XmlElement
    protected BigDecimal mmsndur;
    /**
     * Mean Mission Duration Measurement Base
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected MeasurementBaseType mmsdurmb;
    /**
     * Required Administrative And Logistics Delay Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer reqadldt;
    /**
     * Required Operational Availability
     * 
     */
    @XmlElement
    protected BigDecimal reqopav;
    /**
     * Required Standby Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer reqstbyt;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Maintenance Level Requirement Data
     * 
     */
    @XmlElement(name = "AC")
    protected List<ACType> ac;
    /**
     * Operational Requirement Indicator
     * 
     */
    @XmlAttribute(name = "opreqind", required = true)
    protected OperationalRequirementIndicatorType opreqind;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Additional Requirements
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddreqmt() {
        return addreqmt;
    }

    /**
     * Sets the value of the addreqmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAddreqmt()
     */
    public void setAddreqmt(String value) {
        this.addreqmt = value;
    }

    /**
     * Annual Number of Missions
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnnnomsn() {
        return annnomsn;
    }

    /**
     * Sets the value of the annnomsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAnnnomsn()
     */
    public void setAnnnomsn(Integer value) {
        this.annnomsn = value;
    }

    /**
     * Annual Operating Days
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnnopday() {
        return annopday;
    }

    /**
     * Sets the value of the annopday property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAnnopday()
     */
    public void setAnnopday(Integer value) {
        this.annopday = value;
    }

    /**
     * Annual Operating Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnnoptim() {
        return annoptim;
    }

    /**
     * Sets the value of the annoptim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAnnoptim()
     */
    public void setAnnoptim(Integer value) {
        this.annoptim = value;
    }

    /**
     * Mean Mission Duration
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMmsndur() {
        return mmsndur;
    }

    /**
     * Sets the value of the mmsndur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMmsndur()
     */
    public void setMmsndur(BigDecimal value) {
        this.mmsndur = value;
    }

    /**
     * Mean Mission Duration Measurement Base
     * 
     * @return
     *     possible object is
     *     {@link MeasurementBaseType }
     *     
     */
    public MeasurementBaseType getMmsdurmb() {
        return mmsdurmb;
    }

    /**
     * Sets the value of the mmsdurmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementBaseType }
     *     
     * @see #getMmsdurmb()
     */
    public void setMmsdurmb(MeasurementBaseType value) {
        this.mmsdurmb = value;
    }

    /**
     * Required Administrative And Logistics Delay Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReqadldt() {
        return reqadldt;
    }

    /**
     * Sets the value of the reqadldt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getReqadldt()
     */
    public void setReqadldt(Integer value) {
        this.reqadldt = value;
    }

    /**
     * Required Operational Availability
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReqopav() {
        return reqopav;
    }

    /**
     * Sets the value of the reqopav property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getReqopav()
     */
    public void setReqopav(BigDecimal value) {
        this.reqopav = value;
    }

    /**
     * Required Standby Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReqstbyt() {
        return reqstbyt;
    }

    /**
     * Sets the value of the reqstbyt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getReqstbyt()
     */
    public void setReqstbyt(Integer value) {
        this.reqstbyt = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Maintenance Level Requirement Data
     * 
     * Gets the value of the ac property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ac property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACType }
     * </p>
     * 
     * 
     * @return
     *     The value of the ac property.
     */
    public List<ACType> getAC() {
        if (ac == null) {
            ac = new ArrayList<>();
        }
        return this.ac;
    }

    /**
     * Operational Requirement Indicator
     * 
     * @return
     *     possible object is
     *     {@link OperationalRequirementIndicatorType }
     *     
     */
    public OperationalRequirementIndicatorType getOpreqind() {
        return opreqind;
    }

    /**
     * Sets the value of the opreqind property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalRequirementIndicatorType }
     *     
     * @see #getOpreqind()
     */
    public void setOpreqind(OperationalRequirementIndicatorType value) {
        this.opreqind = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
