//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Defines the various types of Change transactions. This is referenced iin the change_entity_attribute_group.
 * 
 * <p>Java class for action_type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="action_type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="global_delete"/>
 *     <enumeration value="key_field_change_from"/>
 *     <enumeration value="key_field_change_to"/>
 *     <enumeration value="element_change"/>
 *     <enumeration value="element_delete"/>
 *     <enumeration value="add"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "action_type")
@XmlEnum
public enum ActionType {

    @XmlEnumValue("global_delete")
    GLOBAL_DELETE("global_delete"),
    @XmlEnumValue("key_field_change_from")
    KEY_FIELD_CHANGE_FROM("key_field_change_from"),
    @XmlEnumValue("key_field_change_to")
    KEY_FIELD_CHANGE_TO("key_field_change_to"),
    @XmlEnumValue("element_change")
    ELEMENT_CHANGE("element_change"),
    @XmlEnumValue("element_delete")
    ELEMENT_DELETE("element_delete"),
    @XmlEnumValue("add")
    ADD("add");
    private final String value;

    ActionType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ActionType fromValue(String v) {
        for (ActionType c: ActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
