//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for allocation_maintenance_level_function_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="allocation_maintenance_level_function_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="O"/>
 *     <enumeration value="OI"/>
 *     <enumeration value="I"/>
 *     <enumeration value="IW"/>
 *     <enumeration value="D"/>
 *     <enumeration value="I1"/>
 *     <enumeration value="I2"/>
 *     <enumeration value="T3"/>
 *     <enumeration value="T"/>
 *     <enumeration value="F"/>
 *     <enumeration value="H"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "allocation_maintenance_level_function_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum AllocationMaintenanceLevelFunctionType {

    O("O"),
    OI("OI"),
    I("I"),
    IW("IW"),
    D("D"),
    @XmlEnumValue("I1")
    I_1("I1"),
    @XmlEnumValue("I2")
    I_2("I2"),
    @XmlEnumValue("T3")
    T_3("T3"),
    T("T"),
    F("F"),
    H("H");
    private final String value;

    AllocationMaintenanceLevelFunctionType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static AllocationMaintenanceLevelFunctionType fromValue(String v) {
        for (AllocationMaintenanceLevelFunctionType c: AllocationMaintenanceLevelFunctionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
