//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Reliability Centered Maintenance Question and Disposition Data
 * 
 * <p>Java class for BGA_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BGA_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="rcmlqn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="rcmln" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reliability_centered_maintenance_logic_number_Type" />
 *       <attribute name="rcmlt" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reliability_centered_maintenance_logic_type_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BGA_Type", propOrder = {
    "rcmlqn",
    "extension"
})
public class BGAType {

    /**
     * Reliability Centered Maintenance Logic Question Narrative
     * 
     */
    protected String rcmlqn;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected Extension extension;
    /**
     * Reliability Centered Maintenance Logic Number
     * 
     */
    @XmlAttribute(name = "rcmln", required = true)
    protected String rcmln;
    /**
     * Reliability Centered Maintenance Logic Type
     * 
     */
    @XmlAttribute(name = "rcmlt", required = true)
    protected ReliabilityCenteredMaintenanceLogicTypeType rcmlt;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Reliability Centered Maintenance Logic Question Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmlqn() {
        return rcmlqn;
    }

    /**
     * Sets the value of the rcmlqn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmlqn()
     */
    public void setRcmlqn(String value) {
        this.rcmlqn = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * @return
     *     possible object is
     *     {@link Extension }
     *     
     */
    public Extension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extension }
     *     
     * @see #getExtension()
     */
    public void setExtension(Extension value) {
        this.extension = value;
    }

    /**
     * Reliability Centered Maintenance Logic Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmln() {
        return rcmln;
    }

    /**
     * Sets the value of the rcmln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmln()
     */
    public void setRcmln(String value) {
        this.rcmln = value;
    }

    /**
     * Reliability Centered Maintenance Logic Type
     * 
     * @return
     *     possible object is
     *     {@link ReliabilityCenteredMaintenanceLogicTypeType }
     *     
     */
    public ReliabilityCenteredMaintenanceLogicTypeType getRcmlt() {
        return rcmlt;
    }

    /**
     * Sets the value of the rcmlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReliabilityCenteredMaintenanceLogicTypeType }
     *     
     * @see #getRcmlt()
     */
    public void setRcmlt(ReliabilityCenteredMaintenanceLogicTypeType value) {
        this.rcmlt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
