//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Reliability Centered Maintenance Logic Utilized Data
 * 
 * <p>Java class for BG_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BG_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="rcmlu" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reliability_centered_maintenance_logic_utilized_Type" minOccurs="0"/>
 *         <element name="rcmlurn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="BGA" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}BGA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="BGB" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}BGB_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="rcmlui" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reliability_centered_maintenance_logic_utilized_identifier_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BG_Type", propOrder = {
    "rcmlu",
    "rcmlurn",
    "extension",
    "bga",
    "bgb"
})
public class BGType {

    /**
     * Reliability Centered Maintenance Logic Utilized
     * 
     */
    protected String rcmlu;
    /**
     * Reliability Centered Maintenance Logic Utilized Reasoning Narrative
     * 
     */
    protected String rcmlurn;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    @XmlElement(name = "BGA")
    protected List<BGAType> bga;
    @XmlElement(name = "BGB")
    protected List<BGBType> bgb;
    /**
     * Reliability Centered Maintenance Logic Utilized Identifier
     * 
     */
    @XmlAttribute(name = "rcmlui", required = true)
    protected String rcmlui;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Reliability Centered Maintenance Logic Utilized
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmlu() {
        return rcmlu;
    }

    /**
     * Sets the value of the rcmlu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmlu()
     */
    public void setRcmlu(String value) {
        this.rcmlu = value;
    }

    /**
     * Reliability Centered Maintenance Logic Utilized Reasoning Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmlurn() {
        return rcmlurn;
    }

    /**
     * Sets the value of the rcmlurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmlurn()
     */
    public void setRcmlurn(String value) {
        this.rcmlurn = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the bga property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bga property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBGA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BGAType }
     * </p>
     * 
     * 
     * @return
     *     The value of the bga property.
     */
    public List<BGAType> getBGA() {
        if (bga == null) {
            bga = new ArrayList<>();
        }
        return this.bga;
    }

    /**
     * Gets the value of the bgb property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bgb property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBGB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BGBType }
     * </p>
     * 
     * 
     * @return
     *     The value of the bgb property.
     */
    public List<BGBType> getBGB() {
        if (bgb == null) {
            bgb = new ArrayList<>();
        }
        return this.bgb;
    }

    /**
     * Reliability Centered Maintenance Logic Utilized Identifier
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcmlui() {
        return rcmlui;
    }

    /**
     * Sets the value of the rcmlui property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRcmlui()
     */
    public void setRcmlui(String value) {
        this.rcmlui = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
