//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for circuit_breaker_objective_state_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="circuit_breaker_objective_state_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="open"/>
 *     <enumeration value="close"/>
 *     <enumeration value="verify_open"/>
 *     <enumeration value="verify_closed"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "circuit_breaker_objective_state_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum CircuitBreakerObjectiveStateType {

    @XmlEnumValue("open")
    OPEN("open"),
    @XmlEnumValue("close")
    CLOSE("close"),
    @XmlEnumValue("verify_open")
    VERIFY_OPEN("verify_open"),
    @XmlEnumValue("verify_closed")
    VERIFY_CLOSED("verify_closed");
    private final String value;

    CircuitBreakerObjectiveStateType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static CircuitBreakerObjectiveStateType fromValue(String v) {
        for (CircuitBreakerObjectiveStateType c: CircuitBreakerObjectiveStateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
