//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Caution Warning Note Narrative
 * 
 * <p>Java class for CLL_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CLL_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="cwnttle" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}caution_warning_note_title_Type" minOccurs="0"/>
 *         <element name="tastassn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="tastanty" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}task_subtask_associated_narrative_type_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="CLX" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}CLX_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="cwnid" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}caution_warning_note_identifier_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLL_Type", propOrder = {
    "cwnttle",
    "tastassn",
    "tastanty",
    "extension",
    "clx"
})
@XmlSeeAlso({
    com.clanmchperson.geia0007c.FileType.Change.CLL.class
})
public class CLLType {

    /**
     * Caution Warning Note Title
     * 
     */
    @XmlElement
    protected String cwnttle;
    /**
     * Task Subtask Associated Narrative
     * 
     */
    @XmlElement
    protected String tastassn;
    /**
     * Task Subtask Associated Narrative Type
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected TaskSubtaskAssociatedNarrativeTypeType tastanty;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Caution Warning Note Narrative to Digital File Data
     * 
     */
    @XmlElement(name = "CLX")
    protected List<CLXType> clx;
    /**
     * Caution Warning Note Identifier
     * 
     */
    @XmlAttribute(name = "cwnid", required = true)
    protected String cwnid;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Caution Warning Note Title
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCwnttle() {
        return cwnttle;
    }

    /**
     * Sets the value of the cwnttle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCwnttle()
     */
    public void setCwnttle(String value) {
        this.cwnttle = value;
    }

    /**
     * Task Subtask Associated Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTastassn() {
        return tastassn;
    }

    /**
     * Sets the value of the tastassn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTastassn()
     */
    public void setTastassn(String value) {
        this.tastassn = value;
    }

    /**
     * Task Subtask Associated Narrative Type
     * 
     * @return
     *     possible object is
     *     {@link TaskSubtaskAssociatedNarrativeTypeType }
     *     
     */
    public TaskSubtaskAssociatedNarrativeTypeType getTastanty() {
        return tastanty;
    }

    /**
     * Sets the value of the tastanty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskSubtaskAssociatedNarrativeTypeType }
     *     
     * @see #getTastanty()
     */
    public void setTastanty(TaskSubtaskAssociatedNarrativeTypeType value) {
        this.tastanty = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Caution Warning Note Narrative to Digital File Data
     * 
     * Gets the value of the clx property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clx property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCLX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLXType }
     * </p>
     * 
     * 
     * @return
     *     The value of the clx property.
     */
    public List<CLXType> getCLX() {
        if (clx == null) {
            clx = new ArrayList<>();
        }
        return this.clx;
    }

    /**
     * Caution Warning Note Identifier
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCwnid() {
        return cwnid;
    }

    /**
     * Sets the value of the cwnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCwnid()
     */
    public void setCwnid(String value) {
        this.cwnid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
