//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Electronic Documentation Data
 * 
 * <p>Java class for CM_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CM_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="grphsrid" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}graphic_source_identification_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="subtdisc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}disassembly_code_Type" />
 *       <attribute name="subtinfc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}information_code_Type" />
 *       <attribute name="subtiocv" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}information_code_variant_Type" />
 *       <attribute name="subtitlc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}item_location_code_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CM_Type", propOrder = {
    "grphsrid",
    "extension"
})
public class CMType {

    /**
     * Graphic Source Identification
     * 
     */
    @XmlElement
    protected String grphsrid;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Subtask Disassembly Code
     * 
     */
    @XmlAttribute(name = "subtdisc", required = true)
    protected String subtdisc;
    /**
     * Subtask Information Code
     * 
     */
    @XmlAttribute(name = "subtinfc", required = true)
    protected String subtinfc;
    /**
     * Subtask Information Code Variant
     * 
     */
    @XmlAttribute(name = "subtiocv", required = true)
    protected String subtiocv;
    /**
     * Subtask Item Location Code
     * 
     */
    @XmlAttribute(name = "subtitlc", required = true)
    protected ItemLocationCodeType subtitlc;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Graphic Source Identification
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrphsrid() {
        return grphsrid;
    }

    /**
     * Sets the value of the grphsrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getGrphsrid()
     */
    public void setGrphsrid(String value) {
        this.grphsrid = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Subtask Disassembly Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtdisc() {
        return subtdisc;
    }

    /**
     * Sets the value of the subtdisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtdisc()
     */
    public void setSubtdisc(String value) {
        this.subtdisc = value;
    }

    /**
     * Subtask Information Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtinfc() {
        return subtinfc;
    }

    /**
     * Sets the value of the subtinfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtinfc()
     */
    public void setSubtinfc(String value) {
        this.subtinfc = value;
    }

    /**
     * Subtask Information Code Variant
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtiocv() {
        return subtiocv;
    }

    /**
     * Sets the value of the subtiocv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubtiocv()
     */
    public void setSubtiocv(String value) {
        this.subtiocv = value;
    }

    /**
     * Subtask Item Location Code
     * 
     * @return
     *     possible object is
     *     {@link ItemLocationCodeType }
     *     
     */
    public ItemLocationCodeType getSubtitlc() {
        return subtitlc;
    }

    /**
     * Sets the value of the subtitlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemLocationCodeType }
     *     
     * @see #getSubtitlc()
     */
    public void setSubtitlc(ItemLocationCodeType value) {
        this.subtitlc = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
