//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Input Power Source Data
 * 
 * <p>Java class for EI_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EI_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="inpsacdc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_ac_dc_Type" minOccurs="0"/>
 *         <element name="inpsfrmx" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_frequency_range_Type" minOccurs="0"/>
 *         <element name="inpsfrmn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_frequency_range_Type" minOccurs="0"/>
 *         <element name="inpsormx" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_operating_range_Type" minOccurs="0"/>
 *         <element name="inpsormn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_operating_range_Type" minOccurs="0"/>
 *         <element name="inpspmxr" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_percent_maximum_ripple_Type" minOccurs="0"/>
 *         <element name="inpsphas" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_phase_Type" minOccurs="0"/>
 *         <element name="ipswatts" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}input_power_source_watts_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attribute name="srcoptno" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}source_option_number_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EI_Type", propOrder = {
    "inpsacdc",
    "inpsfrmx",
    "inpsfrmn",
    "inpsormx",
    "inpsormn",
    "inpspmxr",
    "inpsphas",
    "ipswatts",
    "extension"
})
public class EIType {

    /**
     * Input Power Source AC DC
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected InputPowerSourceAcDcType inpsacdc;
    /**
     * Input Power Source Frequency Range Maximum
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer inpsfrmx;
    /**
     * Input Power Source Frequency Range Minimum
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer inpsfrmn;
    /**
     * Input Power Source Operating Range Maximum
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer inpsormx;
    /**
     * Input Power Source Operating Range Minimum
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer inpsormn;
    /**
     * Input Power Source Percent Maximum Ripple
     * 
     */
    @XmlElement
    protected BigDecimal inpspmxr;
    /**
     * Input Power Source Phase
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "positiveInteger")
    protected Integer inpsphas;
    /**
     * Input Power Source Watts
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer ipswatts;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Source Option Number
     * 
     */
    @XmlAttribute(name = "srcoptno", required = true)
    protected int srcoptno;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Input Power Source AC DC
     * 
     * @return
     *     possible object is
     *     {@link InputPowerSourceAcDcType }
     *     
     */
    public InputPowerSourceAcDcType getInpsacdc() {
        return inpsacdc;
    }

    /**
     * Sets the value of the inpsacdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputPowerSourceAcDcType }
     *     
     * @see #getInpsacdc()
     */
    public void setInpsacdc(InputPowerSourceAcDcType value) {
        this.inpsacdc = value;
    }

    /**
     * Input Power Source Frequency Range Maximum
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInpsfrmx() {
        return inpsfrmx;
    }

    /**
     * Sets the value of the inpsfrmx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getInpsfrmx()
     */
    public void setInpsfrmx(Integer value) {
        this.inpsfrmx = value;
    }

    /**
     * Input Power Source Frequency Range Minimum
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInpsfrmn() {
        return inpsfrmn;
    }

    /**
     * Sets the value of the inpsfrmn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getInpsfrmn()
     */
    public void setInpsfrmn(Integer value) {
        this.inpsfrmn = value;
    }

    /**
     * Input Power Source Operating Range Maximum
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInpsormx() {
        return inpsormx;
    }

    /**
     * Sets the value of the inpsormx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getInpsormx()
     */
    public void setInpsormx(Integer value) {
        this.inpsormx = value;
    }

    /**
     * Input Power Source Operating Range Minimum
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInpsormn() {
        return inpsormn;
    }

    /**
     * Sets the value of the inpsormn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getInpsormn()
     */
    public void setInpsormn(Integer value) {
        this.inpsormn = value;
    }

    /**
     * Input Power Source Percent Maximum Ripple
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInpspmxr() {
        return inpspmxr;
    }

    /**
     * Sets the value of the inpspmxr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getInpspmxr()
     */
    public void setInpspmxr(BigDecimal value) {
        this.inpspmxr = value;
    }

    /**
     * Input Power Source Phase
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInpsphas() {
        return inpsphas;
    }

    /**
     * Sets the value of the inpsphas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getInpsphas()
     */
    public void setInpsphas(Integer value) {
        this.inpsphas = value;
    }

    /**
     * Input Power Source Watts
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIpswatts() {
        return ipswatts;
    }

    /**
     * Sets the value of the ipswatts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIpswatts()
     */
    public void setIpswatts(Integer value) {
        this.ipswatts = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Source Option Number
     * 
     */
    public int getSrcoptno() {
        return srcoptno;
    }

    /**
     * Sets the value of the srcoptno property.
     * 
     */
    public void setSrcoptno(int value) {
        this.srcoptno = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
