//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Facility Data
 * 
 * <p>Java class for FA_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FA_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="bfacmrn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="bfacron" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="bfacrtn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="bfacrscn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="bfacrssn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="cnstrum" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_of_measure_Type" minOccurs="0"/>
 *         <element name="facarea" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}facility_area_Type" minOccurs="0"/>
 *         <element name="facarum" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_of_measure_Type" minOccurs="0"/>
 *         <element name="faccapn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="facclass" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}facility_class_Type" minOccurs="0"/>
 *         <element name="faccump" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}price_Type" minOccurs="0"/>
 *         <element name="faccumpc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}currency_code_Type" minOccurs="0"/>
 *         <element name="facdrwcl" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}drawing_classification_Type" minOccurs="0"/>
 *         <element name="facdrwno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}drawing_number_Type" minOccurs="0"/>
 *         <element name="facdrwrv" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}revision_Type" minOccurs="0"/>
 *         <element name="faclocn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfdcn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfiltn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfjstn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfreqn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomftabn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomftocn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfucrn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfurn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nomfutln" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="FZ" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}FZ_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attribute name="faccatgc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}facility_category_code_Type" />
 *       <attribute name="facname" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}facility_name_Type" />
 *       <attribute name="factype" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}facility_type_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FA_Type", propOrder = {
    "bfacmrn",
    "bfacron",
    "bfacrtn",
    "bfacrscn",
    "bfacrssn",
    "cnstrum",
    "facarea",
    "facarum",
    "faccapn",
    "facclass",
    "faccump",
    "faccumpc",
    "facdrwcl",
    "facdrwno",
    "facdrwrv",
    "faclocn",
    "nomfdcn",
    "nomfiltn",
    "nomfjstn",
    "nomfreqn",
    "nomftabn",
    "nomftocn",
    "nomfucrn",
    "nomfurn",
    "nomfutln",
    "extension",
    "fz"
})
@XmlSeeAlso({
    com.clanmchperson.geia0007c.FileType.Change.FA.class
})
public class FAType {

    /**
     * Baseline Facility Maintenance Requirement Narrative
     * 
     */
    @XmlElement
    protected String bfacmrn;
    /**
     * Baseline Facility Requirements For Operations Narrative
     * 
     */
    @XmlElement
    protected String bfacron;
    /**
     * Baseline Facility Requirements For Training Narrative
     * 
     */
    @XmlElement
    protected String bfacrtn;
    /**
     * Baseline Facility Requirements Special Considerations Narrative
     * 
     */
    @XmlElement
    protected String bfacrscn;
    /**
     * Baseline Facility Requirements Supply Storage Narrative
     * 
     */
    @XmlElement
    protected String bfacrssn;
    /**
     * Construction Unit Of Measure
     * 
     */
    @XmlElement
    protected String cnstrum;
    /**
     * Facility Area
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer facarea;
    /**
     * Facility Area Unit Of Measure
     * 
     */
    @XmlElement
    protected String facarum;
    /**
     * Facility Capability Narrative
     * 
     */
    @XmlElement
    protected String faccapn;
    /**
     * Facility Class
     * 
     */
    @XmlElement
    protected String facclass;
    /**
     * Facility Construction Unit Of Measure Price
     * 
     */
    @XmlElement
    protected BigDecimal faccump;
    /**
     * Facility Construction Unit Of Measure Price Currency Code
     * 
     */
    @XmlElement
    protected String faccumpc;
    /**
     * Facility Drawing Classification
     * 
     */
    @XmlElement
    protected String facdrwcl;
    /**
     * Facility Drawing Number
     * 
     */
    @XmlElement
    protected String facdrwno;
    /**
     * Facility Drawing Revision
     * 
     */
    @XmlElement
    protected String facdrwrv;
    /**
     * Facility Location Narrative
     * 
     */
    @XmlElement
    protected String faclocn;
    /**
     * New Or Modified Facility Design Criteria Narrative
     * 
     */
    @XmlElement
    protected String nomfdcn;
    /**
     * New Or Modified Facility Installation Lead Time Narrative
     * 
     */
    @XmlElement
    protected String nomfiltn;
    /**
     * New Or Modified Facility Justification Narrative
     * 
     */
    @XmlElement
    protected String nomfjstn;
    /**
     * New Or Modified Facility Requirements Narrative
     * 
     */
    @XmlElement
    protected String nomfreqn;
    /**
     * New Or Modified Facility Task Area Breakdown Narrative
     * 
     */
    @XmlElement
    protected String nomftabn;
    /**
     * New Or Modified Facility Type Of Construction Narrative
     * 
     */
    @XmlElement
    protected String nomftocn;
    /**
     * New Or Modified Facility Unit Cost Rationale Narrative
     * 
     */
    @XmlElement
    protected String nomfucrn;
    /**
     * New Or Modified Facility Utilities Requirement Narrative
     * 
     */
    @XmlElement
    protected String nomfurn;
    /**
     * New Or Modified Facility Utilization Narrative
     * 
     */
    @XmlElement
    protected String nomfutln;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Facility Digital File Data
     * 
     */
    @XmlElement(name = "FZ")
    protected List<FZType> fz;
    /**
     * Facility Category Code
     * 
     */
    @XmlAttribute(name = "faccatgc", required = true)
    protected String faccatgc;
    /**
     * Facility Name
     * 
     */
    @XmlAttribute(name = "facname", required = true)
    protected String facname;
    /**
     * Facility Type
     * 
     */
    @XmlAttribute(name = "factype", required = true)
    protected FacilityTypeType factype;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Baseline Facility Maintenance Requirement Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBfacmrn() {
        return bfacmrn;
    }

    /**
     * Sets the value of the bfacmrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBfacmrn()
     */
    public void setBfacmrn(String value) {
        this.bfacmrn = value;
    }

    /**
     * Baseline Facility Requirements For Operations Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBfacron() {
        return bfacron;
    }

    /**
     * Sets the value of the bfacron property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBfacron()
     */
    public void setBfacron(String value) {
        this.bfacron = value;
    }

    /**
     * Baseline Facility Requirements For Training Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBfacrtn() {
        return bfacrtn;
    }

    /**
     * Sets the value of the bfacrtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBfacrtn()
     */
    public void setBfacrtn(String value) {
        this.bfacrtn = value;
    }

    /**
     * Baseline Facility Requirements Special Considerations Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBfacrscn() {
        return bfacrscn;
    }

    /**
     * Sets the value of the bfacrscn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBfacrscn()
     */
    public void setBfacrscn(String value) {
        this.bfacrscn = value;
    }

    /**
     * Baseline Facility Requirements Supply Storage Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBfacrssn() {
        return bfacrssn;
    }

    /**
     * Sets the value of the bfacrssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBfacrssn()
     */
    public void setBfacrssn(String value) {
        this.bfacrssn = value;
    }

    /**
     * Construction Unit Of Measure
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnstrum() {
        return cnstrum;
    }

    /**
     * Sets the value of the cnstrum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCnstrum()
     */
    public void setCnstrum(String value) {
        this.cnstrum = value;
    }

    /**
     * Facility Area
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFacarea() {
        return facarea;
    }

    /**
     * Sets the value of the facarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getFacarea()
     */
    public void setFacarea(Integer value) {
        this.facarea = value;
    }

    /**
     * Facility Area Unit Of Measure
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacarum() {
        return facarum;
    }

    /**
     * Sets the value of the facarum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacarum()
     */
    public void setFacarum(String value) {
        this.facarum = value;
    }

    /**
     * Facility Capability Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaccapn() {
        return faccapn;
    }

    /**
     * Sets the value of the faccapn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFaccapn()
     */
    public void setFaccapn(String value) {
        this.faccapn = value;
    }

    /**
     * Facility Class
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacclass() {
        return facclass;
    }

    /**
     * Sets the value of the facclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacclass()
     */
    public void setFacclass(String value) {
        this.facclass = value;
    }

    /**
     * Facility Construction Unit Of Measure Price
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaccump() {
        return faccump;
    }

    /**
     * Sets the value of the faccump property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getFaccump()
     */
    public void setFaccump(BigDecimal value) {
        this.faccump = value;
    }

    /**
     * Facility Construction Unit Of Measure Price Currency Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaccumpc() {
        return faccumpc;
    }

    /**
     * Sets the value of the faccumpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFaccumpc()
     */
    public void setFaccumpc(String value) {
        this.faccumpc = value;
    }

    /**
     * Facility Drawing Classification
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacdrwcl() {
        return facdrwcl;
    }

    /**
     * Sets the value of the facdrwcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacdrwcl()
     */
    public void setFacdrwcl(String value) {
        this.facdrwcl = value;
    }

    /**
     * Facility Drawing Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacdrwno() {
        return facdrwno;
    }

    /**
     * Sets the value of the facdrwno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacdrwno()
     */
    public void setFacdrwno(String value) {
        this.facdrwno = value;
    }

    /**
     * Facility Drawing Revision
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacdrwrv() {
        return facdrwrv;
    }

    /**
     * Sets the value of the facdrwrv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacdrwrv()
     */
    public void setFacdrwrv(String value) {
        this.facdrwrv = value;
    }

    /**
     * Facility Location Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaclocn() {
        return faclocn;
    }

    /**
     * Sets the value of the faclocn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFaclocn()
     */
    public void setFaclocn(String value) {
        this.faclocn = value;
    }

    /**
     * New Or Modified Facility Design Criteria Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfdcn() {
        return nomfdcn;
    }

    /**
     * Sets the value of the nomfdcn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfdcn()
     */
    public void setNomfdcn(String value) {
        this.nomfdcn = value;
    }

    /**
     * New Or Modified Facility Installation Lead Time Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfiltn() {
        return nomfiltn;
    }

    /**
     * Sets the value of the nomfiltn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfiltn()
     */
    public void setNomfiltn(String value) {
        this.nomfiltn = value;
    }

    /**
     * New Or Modified Facility Justification Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfjstn() {
        return nomfjstn;
    }

    /**
     * Sets the value of the nomfjstn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfjstn()
     */
    public void setNomfjstn(String value) {
        this.nomfjstn = value;
    }

    /**
     * New Or Modified Facility Requirements Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfreqn() {
        return nomfreqn;
    }

    /**
     * Sets the value of the nomfreqn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfreqn()
     */
    public void setNomfreqn(String value) {
        this.nomfreqn = value;
    }

    /**
     * New Or Modified Facility Task Area Breakdown Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomftabn() {
        return nomftabn;
    }

    /**
     * Sets the value of the nomftabn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomftabn()
     */
    public void setNomftabn(String value) {
        this.nomftabn = value;
    }

    /**
     * New Or Modified Facility Type Of Construction Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomftocn() {
        return nomftocn;
    }

    /**
     * Sets the value of the nomftocn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomftocn()
     */
    public void setNomftocn(String value) {
        this.nomftocn = value;
    }

    /**
     * New Or Modified Facility Unit Cost Rationale Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfucrn() {
        return nomfucrn;
    }

    /**
     * Sets the value of the nomfucrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfucrn()
     */
    public void setNomfucrn(String value) {
        this.nomfucrn = value;
    }

    /**
     * New Or Modified Facility Utilities Requirement Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfurn() {
        return nomfurn;
    }

    /**
     * Sets the value of the nomfurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfurn()
     */
    public void setNomfurn(String value) {
        this.nomfurn = value;
    }

    /**
     * New Or Modified Facility Utilization Narrative
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomfutln() {
        return nomfutln;
    }

    /**
     * Sets the value of the nomfutln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNomfutln()
     */
    public void setNomfutln(String value) {
        this.nomfutln = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Facility Digital File Data
     * 
     * Gets the value of the fz property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fz property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFZ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FZType }
     * </p>
     * 
     * 
     * @return
     *     The value of the fz property.
     */
    public List<FZType> getFZ() {
        if (fz == null) {
            fz = new ArrayList<>();
        }
        return this.fz;
    }

    /**
     * Facility Category Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaccatgc() {
        return faccatgc;
    }

    /**
     * Sets the value of the faccatgc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFaccatgc()
     */
    public void setFaccatgc(String value) {
        this.faccatgc = value;
    }

    /**
     * Facility Name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacname() {
        return facname;
    }

    /**
     * Sets the value of the facname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getFacname()
     */
    public void setFacname(String value) {
        this.facname = value;
    }

    /**
     * Facility Type
     * 
     * @return
     *     possible object is
     *     {@link FacilityTypeType }
     *     
     */
    public FacilityTypeType getFactype() {
        return factype;
    }

    /**
     * Sets the value of the factype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityTypeType }
     *     
     * @see #getFactype()
     */
    public void setFactype(FacilityTypeType value) {
        this.factype = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
