//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Part Hazardous Substance Data
 * 
 * <p>Java class for HAZ_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HAZ_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="submsmax" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}substance_mass_Type" minOccurs="0"/>
 *         <element name="submsmin" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}substance_mass_Type" minOccurs="0"/>
 *         <element name="submsnom" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}substance_mass_Type" minOccurs="0"/>
 *         <element name="submasum" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_of_measure_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="SA_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HAZ_Type", propOrder = {
    "submsmax",
    "submsmin",
    "submsnom",
    "submasum",
    "extension"
})
public class HAZType {

    /**
     * Substance Mass Maximum
     * 
     */
    protected BigDecimal submsmax;
    /**
     * Substance Mass Minimum
     * 
     */
    protected BigDecimal submsmin;
    /**
     * Substance Mass Nominal
     * 
     */
    protected BigDecimal submsnom;
    /**
     * Substance Mass Unit of Measure
     * 
     */
    protected String submasum;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    @XmlAttribute(name = "SA_ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected SAType saRef;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Substance Mass Maximum
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubmsmax() {
        return submsmax;
    }

    /**
     * Sets the value of the submsmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getSubmsmax()
     */
    public void setSubmsmax(BigDecimal value) {
        this.submsmax = value;
    }

    /**
     * Substance Mass Minimum
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubmsmin() {
        return submsmin;
    }

    /**
     * Sets the value of the submsmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getSubmsmin()
     */
    public void setSubmsmin(BigDecimal value) {
        this.submsmin = value;
    }

    /**
     * Substance Mass Nominal
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubmsnom() {
        return submsnom;
    }

    /**
     * Sets the value of the submsnom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getSubmsnom()
     */
    public void setSubmsnom(BigDecimal value) {
        this.submsnom = value;
    }

    /**
     * Substance Mass Unit of Measure
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmasum() {
        return submasum;
    }

    /**
     * Sets the value of the submasum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubmasum()
     */
    public void setSubmasum(String value) {
        this.submasum = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the saRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public SAType getSARef() {
        return saRef;
    }

    /**
     * Sets the value of the saRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSARef(SAType value) {
        this.saRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
