//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Additional National Stock Number Data
 * 
 * <p>Java class for HBA_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HBA_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="justific" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}narrative_Type" minOccurs="0"/>
 *         <element name="nsnactvc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}national_stock_number_activity_code_Type" minOccurs="0"/>
 *         <element name="nsncogc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}national_stock_number_cognizance_code_Type" minOccurs="0"/>
 *         <element name="nsncage" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}commercial_and_government_entity_code_Type" minOccurs="0"/>
 *         <element name="nsnmcc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}national_stock_number_materiel_control_code_Type" minOccurs="0"/>
 *         <element name="nsnrefno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_Type" minOccurs="0"/>
 *         <element name="nsnrncc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_category_code_Type" minOccurs="0"/>
 *         <element name="nsnrnvc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_variation_code_Type" minOccurs="0"/>
 *         <element name="nsnmimma" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}national_stock_number_special_materiel_identification_code_materiel_management_aggregation_code_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="nsnfsc" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}federal_supply_classification_Type" />
 *       <attribute name="nsnniin" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}national_item_identification_number_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HBA_Type", propOrder = {
    "justific",
    "nsnactvc",
    "nsncogc",
    "nsncage",
    "nsnmcc",
    "nsnrefno",
    "nsnrncc",
    "nsnrnvc",
    "nsnmimma",
    "extension"
})
public class HBAType {

    /**
     * Justification
     * 
     */
    @XmlElement
    protected String justific;
    /**
     * Nsn Activity Code
     * 
     */
    @XmlElement
    protected String nsnactvc;
    /**
     * Nsn Cognizance Code
     * 
     */
    @XmlElement
    protected String nsncogc;
    /**
     * Nsn Cage Code
     * 
     */
    @XmlElement
    protected String nsncage;
    /**
     * Nsn Materiel Control Code
     * 
     */
    @XmlElement
    protected String nsnmcc;
    /**
     * Nsn Reference Number
     * 
     */
    @XmlElement
    protected String nsnrefno;
    /**
     * Nsn Reference Number Category Code
     * 
     */
    @XmlElement
    protected String nsnrncc;
    /**
     * Nsn Reference Number Variation Code
     * 
     */
    @XmlElement
    protected String nsnrnvc;
    /**
     * Nsn Special Materiel Identification Code Materiel Management Aggregation Code
     * 
     */
    @XmlElement
    protected String nsnmimma;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * National Stock Number Federal Supply Classification
     * 
     */
    @XmlAttribute(name = "nsnfsc", required = true)
    protected String nsnfsc;
    /**
     * National Stock Number National Item Identification Number
     * 
     */
    @XmlAttribute(name = "nsnniin", required = true)
    protected String nsnniin;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Justification
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustific() {
        return justific;
    }

    /**
     * Sets the value of the justific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getJustific()
     */
    public void setJustific(String value) {
        this.justific = value;
    }

    /**
     * Nsn Activity Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnactvc() {
        return nsnactvc;
    }

    /**
     * Sets the value of the nsnactvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnactvc()
     */
    public void setNsnactvc(String value) {
        this.nsnactvc = value;
    }

    /**
     * Nsn Cognizance Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsncogc() {
        return nsncogc;
    }

    /**
     * Sets the value of the nsncogc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsncogc()
     */
    public void setNsncogc(String value) {
        this.nsncogc = value;
    }

    /**
     * Nsn Cage Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsncage() {
        return nsncage;
    }

    /**
     * Sets the value of the nsncage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsncage()
     */
    public void setNsncage(String value) {
        this.nsncage = value;
    }

    /**
     * Nsn Materiel Control Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnmcc() {
        return nsnmcc;
    }

    /**
     * Sets the value of the nsnmcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnmcc()
     */
    public void setNsnmcc(String value) {
        this.nsnmcc = value;
    }

    /**
     * Nsn Reference Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnrefno() {
        return nsnrefno;
    }

    /**
     * Sets the value of the nsnrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnrefno()
     */
    public void setNsnrefno(String value) {
        this.nsnrefno = value;
    }

    /**
     * Nsn Reference Number Category Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnrncc() {
        return nsnrncc;
    }

    /**
     * Sets the value of the nsnrncc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnrncc()
     */
    public void setNsnrncc(String value) {
        this.nsnrncc = value;
    }

    /**
     * Nsn Reference Number Variation Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnrnvc() {
        return nsnrnvc;
    }

    /**
     * Sets the value of the nsnrnvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnrnvc()
     */
    public void setNsnrnvc(String value) {
        this.nsnrnvc = value;
    }

    /**
     * Nsn Special Materiel Identification Code Materiel Management Aggregation Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnmimma() {
        return nsnmimma;
    }

    /**
     * Sets the value of the nsnmimma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnmimma()
     */
    public void setNsnmimma(String value) {
        this.nsnmimma = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * National Stock Number Federal Supply Classification
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnfsc() {
        return nsnfsc;
    }

    /**
     * Sets the value of the nsnfsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnfsc()
     */
    public void setNsnfsc(String value) {
        this.nsnfsc = value;
    }

    /**
     * National Stock Number National Item Identification Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsnniin() {
        return nsnniin;
    }

    /**
     * Sets the value of the nsnniin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNsnniin()
     */
    public void setNsnniin(String value) {
        this.nsnniin = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
