//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Additional Reference Number Data
 * 
 * <p>Java class for HB_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HB_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="arnrncc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_category_code_Type" minOccurs="0"/>
 *         <element name="arnrnvc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_variation_code_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attribute name="arn" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}reference_number_Type" />
 *       <attribute name="XH_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HB_Type", propOrder = {
    "arnrncc",
    "arnrnvc",
    "extension"
})
public class HBType {

    /**
     * Additional Reference Number Reference Number Category Code
     * 
     */
    @XmlElement
    protected String arnrncc;
    /**
     * Additional Reference Number Reference Number Variation Code
     * 
     */
    @XmlElement
    protected String arnrnvc;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Additional Reference Number
     * 
     */
    @XmlAttribute(name = "arn", required = true)
    protected String arn;
    @XmlAttribute(name = "XH_ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected XHType xhRef;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Additional Reference Number Reference Number Category Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArnrncc() {
        return arnrncc;
    }

    /**
     * Sets the value of the arnrncc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getArnrncc()
     */
    public void setArnrncc(String value) {
        this.arnrncc = value;
    }

    /**
     * Additional Reference Number Reference Number Variation Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArnrnvc() {
        return arnrnvc;
    }

    /**
     * Sets the value of the arnrnvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getArnrnvc()
     */
    public void setArnrnvc(String value) {
        this.arnrnvc = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Additional Reference Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArn() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getArn()
     */
    public void setArn(String value) {
        this.arn = value;
    }

    /**
     * Gets the value of the xhRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public XHType getXHRef() {
        return xhRef;
    }

    /**
     * Sets the value of the xhRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXHRef(XHType value) {
        this.xhRef = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
