//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Part Application Provisioning Data
 * 
 * <p>Java class for HG_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HG_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="allwitcd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}allowance_item_code_Type" minOccurs="0"/>
 *         <element name="allwitqt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}allowance_item_quantity_Type" minOccurs="0"/>
 *         <element name="araptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="arbptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="cbilptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="cndadmtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="cndbdmtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="cntrrpct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="datastac" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}data_status_code_Type" minOccurs="0"/>
 *         <element name="dshpymtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="dshpyrct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="dshpyrtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replacement_task_distribution_Type" minOccurs="0"/>
 *         <element name="dsgrwpt1" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}designated_rework_point_Type" minOccurs="0"/>
 *         <element name="dsgrwpt2" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}designated_rework_point_Type" minOccurs="0"/>
 *         <element name="essntcod" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}essentiality_code_Type" minOccurs="0"/>
 *         <element name="hardcrit" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}hardness_critical_item_Type" minOccurs="0"/>
 *         <element name="idno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}identification_number_Type" minOccurs="0"/>
 *         <element name="ic" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}indenture_code_Type" minOccurs="0"/>
 *         <element name="isilptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="intdsmtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="intdsrct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="intdsrtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replacement_task_distribution_Type" minOccurs="0"/>
 *         <element name="intgsmtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="intdgrct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="intdgrtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replacement_task_distribution_Type" minOccurs="0"/>
 *         <element name="icc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}item_category_code_Type" minOccurs="0"/>
 *         <element name="lru" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}line_replaceable_unit_Type" minOccurs="0"/>
 *         <element name="lltilptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="mntactnc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_action_code_Type" minOccurs="0"/>
 *         <element name="mrri" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_replacement_rate_i_Type" minOccurs="0"/>
 *         <element name="mrrii" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_replacement_rate_ii_Type" minOccurs="0"/>
 *         <element name="mrrm" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_replacement_rate_modifier_Type" minOccurs="0"/>
 *         <element name="maxalopt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maximum_allowable_operating_time_Type" minOccurs="0"/>
 *         <element name="minrplut" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}minimum_replacement_unit_Type" minOccurs="0"/>
 *         <element name="notrtsta" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}not_repairable_this_station_Type" minOccurs="0"/>
 *         <element name="orgmtdst" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="orgrepct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="orgrtdst" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replacement_task_distribution_Type" minOccurs="0"/>
 *         <element name="pclptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="priplisn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_list_item_sequence_number_Type" minOccurs="0"/>
 *         <element name="plisn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_list_item_sequence_number_Type" minOccurs="0"/>
 *         <element name="pplptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="premarks" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_remarks_Type" minOccurs="0"/>
 *         <element name="psysidc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_system_identifier_code_Type" minOccurs="0"/>
 *         <element name="qpa" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_assembly_Type" minOccurs="0"/>
 *         <element name="qpei" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_end_item_Type" minOccurs="0"/>
 *         <element name="rinisysb" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}recommended_initial_system_stock_buy_Type" minOccurs="0"/>
 *         <element name="rmsystlv" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}recommended_minimum_system_stock_level_Type" minOccurs="0"/>
 *         <element name="rtll" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}recommended_tender_load_list_quantity_Type" minOccurs="0"/>
 *         <element name="ripindct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}remain_in_place_indicator_Type" minOccurs="0"/>
 *         <element name="rprsrvrt" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_survival_rate_Type" minOccurs="0"/>
 *         <element name="rilptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="saplisn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_list_item_sequence_number_Type" minOccurs="0"/>
 *         <element name="sfpplptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="srcmtrcc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}source_maintenance_recoverability_code_Type" minOccurs="0"/>
 *         <element name="spamtd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}maintenance_task_distribution_Type" minOccurs="0"/>
 *         <element name="sprarct" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}repair_cycle_time_Type" minOccurs="0"/>
 *         <element name="sprartd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replacement_task_distribution_Type" minOccurs="0"/>
 *         <element name="suprsind" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}supression_indicator_Type" minOccurs="0"/>
 *         <element name="scplptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="ttlptd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_technical_documentation_Type" minOccurs="0"/>
 *         <element name="ttqtyrec" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}total_quantity_recommended_Type" minOccurs="0"/>
 *         <element name="typechgc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}type_of_change_code_Type" minOccurs="0"/>
 *         <element name="wuc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}work_unit_code_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HGA" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HGA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HH" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HH_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HJ" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HJ_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HK" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HK_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HN" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HN_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HO" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HO_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HP" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HP_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HY" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HY_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attribute name="XB_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HG_Type", propOrder = {
    "allwitcd",
    "allwitqt",
    "araptd",
    "arbptd",
    "cbilptd",
    "cndadmtd",
    "cndbdmtd",
    "cntrrpct",
    "datastac",
    "dshpymtd",
    "dshpyrct",
    "dshpyrtd",
    "dsgrwpt1",
    "dsgrwpt2",
    "essntcod",
    "hardcrit",
    "idno",
    "ic",
    "isilptd",
    "intdsmtd",
    "intdsrct",
    "intdsrtd",
    "intgsmtd",
    "intdgrct",
    "intdgrtd",
    "icc",
    "lru",
    "lltilptd",
    "mntactnc",
    "mrri",
    "mrrii",
    "mrrm",
    "maxalopt",
    "minrplut",
    "notrtsta",
    "orgmtdst",
    "orgrepct",
    "orgrtdst",
    "pclptd",
    "priplisn",
    "plisn",
    "pplptd",
    "premarks",
    "psysidc",
    "qpa",
    "qpei",
    "rinisysb",
    "rmsystlv",
    "rtll",
    "ripindct",
    "rprsrvrt",
    "rilptd",
    "saplisn",
    "sfpplptd",
    "srcmtrcc",
    "spamtd",
    "sprarct",
    "sprartd",
    "suprsind",
    "scplptd",
    "ttlptd",
    "ttqtyrec",
    "typechgc",
    "wuc",
    "extension",
    "hga",
    "hh",
    "hj",
    "hk",
    "hn",
    "ho",
    "hp",
    "hy"
})
public class HGType {

    /**
     * Allowance Item Code
     * 
     */
    @XmlElement
    protected String allwitcd;
    /**
     * Allowance Item Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "positiveInteger")
    protected Integer allwitqt;
    /**
     * As Required List A Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean araptd;
    /**
     * As Required List B Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean arbptd;
    /**
     * Common And Bulk Items List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean cbilptd;
    /**
     * Condemned At Depot Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer cndadmtd;
    /**
     * Condemned Below Depot Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer cndbdmtd;
    /**
     * Contractor Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer cntrrpct;
    /**
     * Data Status Code
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected DataStatusCodeType datastac;
    /**
     * Depot Shipyard Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer dshpymtd;
    /**
     * Depot Shipyard Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer dshpyrct;
    /**
     * Depot Shipyard Replacement Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer dshpyrtd;
    /**
     * Designated Rework Point One
     * 
     */
    @XmlElement
    protected String dsgrwpt1;
    /**
     * Designated Rework Point Two
     * 
     */
    @XmlElement
    protected String dsgrwpt2;
    /**
     * Essentiality Code
     * 
     */
    @XmlElement
    protected String essntcod;
    /**
     * Hardness Critical Item
     * 
     */
    @XmlElement
    protected Boolean hardcrit;
    /**
     * Identification Number
     * 
     */
    @XmlElement
    protected String idno;
    /**
     * Indenture Code
     * 
     */
    @XmlElement
    protected String ic;
    /**
     * Interim Support Items List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean isilptd;
    /**
     * Intermediate Direct Support Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intdsmtd;
    /**
     * Intermediate Direct Support Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intdsrct;
    /**
     * Intermediate Direct Support Replacement Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intdsrtd;
    /**
     * Intermediate General Support Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intgsmtd;
    /**
     * Intermediate General Support Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intdgrct;
    /**
     * Intermediate General Support Replacement Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer intdgrtd;
    /**
     * Item Category Code
     * 
     */
    @XmlElement
    protected String icc;
    /**
     * Line Replaceable Unit
     * 
     */
    @XmlElement
    protected Boolean lru;
    /**
     * Long Lead Time Items List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean lltilptd;
    /**
     * Maintenance Action Code
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected MaintenanceActionCodeType mntactnc;
    /**
     * Maintenance Replacement Rate I
     * 
     */
    @XmlElement
    protected BigDecimal mrri;
    /**
     * Maintenance Replacement Rate Ii
     * 
     */
    @XmlElement
    protected BigDecimal mrrii;
    /**
     * Maintenance Replacement Rate Modifier
     * 
     */
    @XmlElement
    protected String mrrm;
    /**
     * Maximum Allowable Operating Time
     * 
     */
    @XmlElement
    protected String maxalopt;
    /**
     * Minimum Replacement Unit
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer minrplut;
    /**
     * Not Repairable This Station
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer notrtsta;
    /**
     * Organizational Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer orgmtdst;
    /**
     * Organizational Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer orgrepct;
    /**
     * Organizational Replacement Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer orgrtdst;
    /**
     * Post Conference List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean pclptd;
    /**
     * Prior Item Provisioning List Item Sequence Number
     * 
     */
    @XmlElement
    protected String priplisn;
    /**
     * Provisioning List Item Sequence Number
     * 
     */
    @XmlElement
    protected String plisn;
    /**
     * Provisioning Parts List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean pplptd;
    /**
     * Provisioning Remarks
     * 
     */
    @XmlElement
    protected String premarks;
    /**
     * Provisioning System Identifier Code
     * 
     */
    @XmlElement
    protected String psysidc;
    /**
     * Quantity Per Assembly
     * 
     */
    @XmlElement
    protected String qpa;
    /**
     * Quantity Per End Item
     * 
     */
    @XmlElement
    protected String qpei;
    /**
     * Recommended Initial System Stock Buy
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer rinisysb;
    /**
     * Recommended Minimum System Stock Level
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer rmsystlv;
    /**
     * Recommended Tender Load List Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer rtll;
    /**
     * Remain In Place Indicator
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected RemainInPlaceIndicatorType ripindct;
    /**
     * Repair Survival Rate
     * 
     */
    @XmlElement
    protected BigInteger rprsrvrt;
    /**
     * Repairable Items List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean rilptd;
    /**
     * Same As Provisioning List Item Sequence Number
     * 
     */
    @XmlElement
    protected String saplisn;
    /**
     * Short Form Provisioning Parts List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean sfpplptd;
    /**
     * Source Maintenance And Recoverability Code
     * 
     */
    @XmlElement
    protected String srcmtrcc;
    /**
     * Special Repair Activity Maintenance Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer spamtd;
    /**
     * Special Repair Activity Repair Cycle Time
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer sprarct;
    /**
     * Special Repair Activity Replacement Task Distribution
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer sprartd;
    /**
     * Supression Indicator
     * 
     */
    @XmlElement
    protected Boolean suprsind;
    /**
     * System Configuration Provisioning Parts List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean scplptd;
    /**
     * Tool And Test Equipment List Provisioning Technical Documentation
     * 
     */
    @XmlElement
    protected Boolean ttlptd;
    /**
     * Total Quantity Recommended
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer ttqtyrec;
    /**
     * Type Of Change Code
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected TypeOfChangeCodeType typechgc;
    /**
     * Work Unit Code
     * 
     */
    @XmlElement
    protected String wuc;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Circuit Breaker Part Application Identifier Data
     * 
     */
    @XmlElement(name = "HGA")
    protected List<HGAType> hga;
    /**
     * Overhaul Kit Next Higher Assembly Provisioning List Item Sequence Number Data
     * 
     */
    @XmlElement(name = "HH")
    protected List<HHType> hh;
    /**
     * Provisioning Reference Designation Data
     * 
     */
    @XmlElement(name = "HJ")
    protected List<HJType> hj;
    /**
     * Parts Manual Description Data
     * 
     */
    @XmlElement(name = "HK")
    protected List<HKType> hk;
    /**
     * Provisioning Serial Number Usable On Code Data
     * 
     */
    @XmlElement(name = "HN")
    protected List<HNType> hn;
    /**
     * Provisioning System End Item Usable On Code Data
     * 
     */
    @XmlElement(name = "HO")
    protected List<HOType> ho;
    /**
     * Design Change Information Data
     * 
     */
    @XmlElement(name = "HP")
    protected List<HPType> hp;
    /**
     * Part Application Identification Digital File Data
     * 
     */
    @XmlElement(name = "HY")
    protected List<HYType> hy;
    @XmlAttribute(name = "XB_ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected XBType xbRef;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Allowance Item Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllwitcd() {
        return allwitcd;
    }

    /**
     * Sets the value of the allwitcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAllwitcd()
     */
    public void setAllwitcd(String value) {
        this.allwitcd = value;
    }

    /**
     * Allowance Item Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAllwitqt() {
        return allwitqt;
    }

    /**
     * Sets the value of the allwitqt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAllwitqt()
     */
    public void setAllwitqt(Integer value) {
        this.allwitqt = value;
    }

    /**
     * As Required List A Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAraptd() {
        return araptd;
    }

    /**
     * Sets the value of the araptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getAraptd()
     */
    public void setAraptd(Boolean value) {
        this.araptd = value;
    }

    /**
     * As Required List B Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getArbptd() {
        return arbptd;
    }

    /**
     * Sets the value of the arbptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getArbptd()
     */
    public void setArbptd(Boolean value) {
        this.arbptd = value;
    }

    /**
     * Common And Bulk Items List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCbilptd() {
        return cbilptd;
    }

    /**
     * Sets the value of the cbilptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getCbilptd()
     */
    public void setCbilptd(Boolean value) {
        this.cbilptd = value;
    }

    /**
     * Condemned At Depot Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCndadmtd() {
        return cndadmtd;
    }

    /**
     * Sets the value of the cndadmtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getCndadmtd()
     */
    public void setCndadmtd(Integer value) {
        this.cndadmtd = value;
    }

    /**
     * Condemned Below Depot Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCndbdmtd() {
        return cndbdmtd;
    }

    /**
     * Sets the value of the cndbdmtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getCndbdmtd()
     */
    public void setCndbdmtd(Integer value) {
        this.cndbdmtd = value;
    }

    /**
     * Contractor Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCntrrpct() {
        return cntrrpct;
    }

    /**
     * Sets the value of the cntrrpct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getCntrrpct()
     */
    public void setCntrrpct(Integer value) {
        this.cntrrpct = value;
    }

    /**
     * Data Status Code
     * 
     * @return
     *     possible object is
     *     {@link DataStatusCodeType }
     *     
     */
    public DataStatusCodeType getDatastac() {
        return datastac;
    }

    /**
     * Sets the value of the datastac property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataStatusCodeType }
     *     
     * @see #getDatastac()
     */
    public void setDatastac(DataStatusCodeType value) {
        this.datastac = value;
    }

    /**
     * Depot Shipyard Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDshpymtd() {
        return dshpymtd;
    }

    /**
     * Sets the value of the dshpymtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getDshpymtd()
     */
    public void setDshpymtd(Integer value) {
        this.dshpymtd = value;
    }

    /**
     * Depot Shipyard Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDshpyrct() {
        return dshpyrct;
    }

    /**
     * Sets the value of the dshpyrct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getDshpyrct()
     */
    public void setDshpyrct(Integer value) {
        this.dshpyrct = value;
    }

    /**
     * Depot Shipyard Replacement Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDshpyrtd() {
        return dshpyrtd;
    }

    /**
     * Sets the value of the dshpyrtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getDshpyrtd()
     */
    public void setDshpyrtd(Integer value) {
        this.dshpyrtd = value;
    }

    /**
     * Designated Rework Point One
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsgrwpt1() {
        return dsgrwpt1;
    }

    /**
     * Sets the value of the dsgrwpt1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDsgrwpt1()
     */
    public void setDsgrwpt1(String value) {
        this.dsgrwpt1 = value;
    }

    /**
     * Designated Rework Point Two
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsgrwpt2() {
        return dsgrwpt2;
    }

    /**
     * Sets the value of the dsgrwpt2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDsgrwpt2()
     */
    public void setDsgrwpt2(String value) {
        this.dsgrwpt2 = value;
    }

    /**
     * Essentiality Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEssntcod() {
        return essntcod;
    }

    /**
     * Sets the value of the essntcod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getEssntcod()
     */
    public void setEssntcod(String value) {
        this.essntcod = value;
    }

    /**
     * Hardness Critical Item
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getHardcrit() {
        return hardcrit;
    }

    /**
     * Sets the value of the hardcrit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getHardcrit()
     */
    public void setHardcrit(Boolean value) {
        this.hardcrit = value;
    }

    /**
     * Identification Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdno() {
        return idno;
    }

    /**
     * Sets the value of the idno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIdno()
     */
    public void setIdno(String value) {
        this.idno = value;
    }

    /**
     * Indenture Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIc() {
        return ic;
    }

    /**
     * Sets the value of the ic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIc()
     */
    public void setIc(String value) {
        this.ic = value;
    }

    /**
     * Interim Support Items List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsilptd() {
        return isilptd;
    }

    /**
     * Sets the value of the isilptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getIsilptd()
     */
    public void setIsilptd(Boolean value) {
        this.isilptd = value;
    }

    /**
     * Intermediate Direct Support Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntdsmtd() {
        return intdsmtd;
    }

    /**
     * Sets the value of the intdsmtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntdsmtd()
     */
    public void setIntdsmtd(Integer value) {
        this.intdsmtd = value;
    }

    /**
     * Intermediate Direct Support Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntdsrct() {
        return intdsrct;
    }

    /**
     * Sets the value of the intdsrct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntdsrct()
     */
    public void setIntdsrct(Integer value) {
        this.intdsrct = value;
    }

    /**
     * Intermediate Direct Support Replacement Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntdsrtd() {
        return intdsrtd;
    }

    /**
     * Sets the value of the intdsrtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntdsrtd()
     */
    public void setIntdsrtd(Integer value) {
        this.intdsrtd = value;
    }

    /**
     * Intermediate General Support Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntgsmtd() {
        return intgsmtd;
    }

    /**
     * Sets the value of the intgsmtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntgsmtd()
     */
    public void setIntgsmtd(Integer value) {
        this.intgsmtd = value;
    }

    /**
     * Intermediate General Support Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntdgrct() {
        return intdgrct;
    }

    /**
     * Sets the value of the intdgrct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntdgrct()
     */
    public void setIntdgrct(Integer value) {
        this.intdgrct = value;
    }

    /**
     * Intermediate General Support Replacement Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntdgrtd() {
        return intdgrtd;
    }

    /**
     * Sets the value of the intdgrtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIntdgrtd()
     */
    public void setIntdgrtd(Integer value) {
        this.intdgrtd = value;
    }

    /**
     * Item Category Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcc() {
        return icc;
    }

    /**
     * Sets the value of the icc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIcc()
     */
    public void setIcc(String value) {
        this.icc = value;
    }

    /**
     * Line Replaceable Unit
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getLru() {
        return lru;
    }

    /**
     * Sets the value of the lru property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getLru()
     */
    public void setLru(Boolean value) {
        this.lru = value;
    }

    /**
     * Long Lead Time Items List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getLltilptd() {
        return lltilptd;
    }

    /**
     * Sets the value of the lltilptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getLltilptd()
     */
    public void setLltilptd(Boolean value) {
        this.lltilptd = value;
    }

    /**
     * Maintenance Action Code
     * 
     * @return
     *     possible object is
     *     {@link MaintenanceActionCodeType }
     *     
     */
    public MaintenanceActionCodeType getMntactnc() {
        return mntactnc;
    }

    /**
     * Sets the value of the mntactnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaintenanceActionCodeType }
     *     
     * @see #getMntactnc()
     */
    public void setMntactnc(MaintenanceActionCodeType value) {
        this.mntactnc = value;
    }

    /**
     * Maintenance Replacement Rate I
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMrri() {
        return mrri;
    }

    /**
     * Sets the value of the mrri property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMrri()
     */
    public void setMrri(BigDecimal value) {
        this.mrri = value;
    }

    /**
     * Maintenance Replacement Rate Ii
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMrrii() {
        return mrrii;
    }

    /**
     * Sets the value of the mrrii property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMrrii()
     */
    public void setMrrii(BigDecimal value) {
        this.mrrii = value;
    }

    /**
     * Maintenance Replacement Rate Modifier
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrrm() {
        return mrrm;
    }

    /**
     * Sets the value of the mrrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMrrm()
     */
    public void setMrrm(String value) {
        this.mrrm = value;
    }

    /**
     * Maximum Allowable Operating Time
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxalopt() {
        return maxalopt;
    }

    /**
     * Sets the value of the maxalopt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMaxalopt()
     */
    public void setMaxalopt(String value) {
        this.maxalopt = value;
    }

    /**
     * Minimum Replacement Unit
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinrplut() {
        return minrplut;
    }

    /**
     * Sets the value of the minrplut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getMinrplut()
     */
    public void setMinrplut(Integer value) {
        this.minrplut = value;
    }

    /**
     * Not Repairable This Station
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNotrtsta() {
        return notrtsta;
    }

    /**
     * Sets the value of the notrtsta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getNotrtsta()
     */
    public void setNotrtsta(Integer value) {
        this.notrtsta = value;
    }

    /**
     * Organizational Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrgmtdst() {
        return orgmtdst;
    }

    /**
     * Sets the value of the orgmtdst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOrgmtdst()
     */
    public void setOrgmtdst(Integer value) {
        this.orgmtdst = value;
    }

    /**
     * Organizational Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrgrepct() {
        return orgrepct;
    }

    /**
     * Sets the value of the orgrepct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOrgrepct()
     */
    public void setOrgrepct(Integer value) {
        this.orgrepct = value;
    }

    /**
     * Organizational Replacement Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrgrtdst() {
        return orgrtdst;
    }

    /**
     * Sets the value of the orgrtdst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOrgrtdst()
     */
    public void setOrgrtdst(Integer value) {
        this.orgrtdst = value;
    }

    /**
     * Post Conference List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPclptd() {
        return pclptd;
    }

    /**
     * Sets the value of the pclptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getPclptd()
     */
    public void setPclptd(Boolean value) {
        this.pclptd = value;
    }

    /**
     * Prior Item Provisioning List Item Sequence Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriplisn() {
        return priplisn;
    }

    /**
     * Sets the value of the priplisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPriplisn()
     */
    public void setPriplisn(String value) {
        this.priplisn = value;
    }

    /**
     * Provisioning List Item Sequence Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlisn() {
        return plisn;
    }

    /**
     * Sets the value of the plisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPlisn()
     */
    public void setPlisn(String value) {
        this.plisn = value;
    }

    /**
     * Provisioning Parts List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPplptd() {
        return pplptd;
    }

    /**
     * Sets the value of the pplptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getPplptd()
     */
    public void setPplptd(Boolean value) {
        this.pplptd = value;
    }

    /**
     * Provisioning Remarks
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremarks() {
        return premarks;
    }

    /**
     * Sets the value of the premarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPremarks()
     */
    public void setPremarks(String value) {
        this.premarks = value;
    }

    /**
     * Provisioning System Identifier Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsysidc() {
        return psysidc;
    }

    /**
     * Sets the value of the psysidc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPsysidc()
     */
    public void setPsysidc(String value) {
        this.psysidc = value;
    }

    /**
     * Quantity Per Assembly
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQpa() {
        return qpa;
    }

    /**
     * Sets the value of the qpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getQpa()
     */
    public void setQpa(String value) {
        this.qpa = value;
    }

    /**
     * Quantity Per End Item
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQpei() {
        return qpei;
    }

    /**
     * Sets the value of the qpei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getQpei()
     */
    public void setQpei(String value) {
        this.qpei = value;
    }

    /**
     * Recommended Initial System Stock Buy
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRinisysb() {
        return rinisysb;
    }

    /**
     * Sets the value of the rinisysb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getRinisysb()
     */
    public void setRinisysb(Integer value) {
        this.rinisysb = value;
    }

    /**
     * Recommended Minimum System Stock Level
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRmsystlv() {
        return rmsystlv;
    }

    /**
     * Sets the value of the rmsystlv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getRmsystlv()
     */
    public void setRmsystlv(Integer value) {
        this.rmsystlv = value;
    }

    /**
     * Recommended Tender Load List Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRtll() {
        return rtll;
    }

    /**
     * Sets the value of the rtll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getRtll()
     */
    public void setRtll(Integer value) {
        this.rtll = value;
    }

    /**
     * Remain In Place Indicator
     * 
     * @return
     *     possible object is
     *     {@link RemainInPlaceIndicatorType }
     *     
     */
    public RemainInPlaceIndicatorType getRipindct() {
        return ripindct;
    }

    /**
     * Sets the value of the ripindct property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemainInPlaceIndicatorType }
     *     
     * @see #getRipindct()
     */
    public void setRipindct(RemainInPlaceIndicatorType value) {
        this.ripindct = value;
    }

    /**
     * Repair Survival Rate
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRprsrvrt() {
        return rprsrvrt;
    }

    /**
     * Sets the value of the rprsrvrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getRprsrvrt()
     */
    public void setRprsrvrt(BigInteger value) {
        this.rprsrvrt = value;
    }

    /**
     * Repairable Items List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRilptd() {
        return rilptd;
    }

    /**
     * Sets the value of the rilptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getRilptd()
     */
    public void setRilptd(Boolean value) {
        this.rilptd = value;
    }

    /**
     * Same As Provisioning List Item Sequence Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaplisn() {
        return saplisn;
    }

    /**
     * Sets the value of the saplisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSaplisn()
     */
    public void setSaplisn(String value) {
        this.saplisn = value;
    }

    /**
     * Short Form Provisioning Parts List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSfpplptd() {
        return sfpplptd;
    }

    /**
     * Sets the value of the sfpplptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getSfpplptd()
     */
    public void setSfpplptd(Boolean value) {
        this.sfpplptd = value;
    }

    /**
     * Source Maintenance And Recoverability Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcmtrcc() {
        return srcmtrcc;
    }

    /**
     * Sets the value of the srcmtrcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSrcmtrcc()
     */
    public void setSrcmtrcc(String value) {
        this.srcmtrcc = value;
    }

    /**
     * Special Repair Activity Maintenance Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpamtd() {
        return spamtd;
    }

    /**
     * Sets the value of the spamtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSpamtd()
     */
    public void setSpamtd(Integer value) {
        this.spamtd = value;
    }

    /**
     * Special Repair Activity Repair Cycle Time
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSprarct() {
        return sprarct;
    }

    /**
     * Sets the value of the sprarct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSprarct()
     */
    public void setSprarct(Integer value) {
        this.sprarct = value;
    }

    /**
     * Special Repair Activity Replacement Task Distribution
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSprartd() {
        return sprartd;
    }

    /**
     * Sets the value of the sprartd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSprartd()
     */
    public void setSprartd(Integer value) {
        this.sprartd = value;
    }

    /**
     * Supression Indicator
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSuprsind() {
        return suprsind;
    }

    /**
     * Sets the value of the suprsind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getSuprsind()
     */
    public void setSuprsind(Boolean value) {
        this.suprsind = value;
    }

    /**
     * System Configuration Provisioning Parts List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getScplptd() {
        return scplptd;
    }

    /**
     * Sets the value of the scplptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getScplptd()
     */
    public void setScplptd(Boolean value) {
        this.scplptd = value;
    }

    /**
     * Tool And Test Equipment List Provisioning Technical Documentation
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTtlptd() {
        return ttlptd;
    }

    /**
     * Sets the value of the ttlptd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getTtlptd()
     */
    public void setTtlptd(Boolean value) {
        this.ttlptd = value;
    }

    /**
     * Total Quantity Recommended
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTtqtyrec() {
        return ttqtyrec;
    }

    /**
     * Sets the value of the ttqtyrec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTtqtyrec()
     */
    public void setTtqtyrec(Integer value) {
        this.ttqtyrec = value;
    }

    /**
     * Type Of Change Code
     * 
     * @return
     *     possible object is
     *     {@link TypeOfChangeCodeType }
     *     
     */
    public TypeOfChangeCodeType getTypechgc() {
        return typechgc;
    }

    /**
     * Sets the value of the typechgc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfChangeCodeType }
     *     
     * @see #getTypechgc()
     */
    public void setTypechgc(TypeOfChangeCodeType value) {
        this.typechgc = value;
    }

    /**
     * Work Unit Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWuc() {
        return wuc;
    }

    /**
     * Sets the value of the wuc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getWuc()
     */
    public void setWuc(String value) {
        this.wuc = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Circuit Breaker Part Application Identifier Data
     * 
     * Gets the value of the hga property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hga property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHGA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HGAType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hga property.
     */
    public List<HGAType> getHGA() {
        if (hga == null) {
            hga = new ArrayList<>();
        }
        return this.hga;
    }

    /**
     * Overhaul Kit Next Higher Assembly Provisioning List Item Sequence Number Data
     * 
     * Gets the value of the hh property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hh property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HHType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hh property.
     */
    public List<HHType> getHH() {
        if (hh == null) {
            hh = new ArrayList<>();
        }
        return this.hh;
    }

    /**
     * Provisioning Reference Designation Data
     * 
     * Gets the value of the hj property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hj property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHJ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HJType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hj property.
     */
    public List<HJType> getHJ() {
        if (hj == null) {
            hj = new ArrayList<>();
        }
        return this.hj;
    }

    /**
     * Parts Manual Description Data
     * 
     * Gets the value of the hk property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hk property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HKType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hk property.
     */
    public List<HKType> getHK() {
        if (hk == null) {
            hk = new ArrayList<>();
        }
        return this.hk;
    }

    /**
     * Provisioning Serial Number Usable On Code Data
     * 
     * Gets the value of the hn property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hn property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HNType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hn property.
     */
    public List<HNType> getHN() {
        if (hn == null) {
            hn = new ArrayList<>();
        }
        return this.hn;
    }

    /**
     * Provisioning System End Item Usable On Code Data
     * 
     * Gets the value of the ho property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ho property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HOType }
     * </p>
     * 
     * 
     * @return
     *     The value of the ho property.
     */
    public List<HOType> getHO() {
        if (ho == null) {
            ho = new ArrayList<>();
        }
        return this.ho;
    }

    /**
     * Design Change Information Data
     * 
     * Gets the value of the hp property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hp property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HPType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hp property.
     */
    public List<HPType> getHP() {
        if (hp == null) {
            hp = new ArrayList<>();
        }
        return this.hp;
    }

    /**
     * Part Application Identification Digital File Data
     * 
     * Gets the value of the hy property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hy property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HYType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hy property.
     */
    public List<HYType> getHY() {
        if (hy == null) {
            hy = new ArrayList<>();
        }
        return this.hy;
    }

    /**
     * Gets the value of the xbRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public XBType getXBRef() {
        return xbRef;
    }

    /**
     * Sets the value of the xbRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXBRef(XBType value) {
        this.xbRef = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
