//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Design Change Information Data
 * 
 * <p>Java class for HP_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HP_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="intrcan" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}interchangeability_code_Type" minOccurs="0"/>
 *         <element name="prexlino" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}prorated_exhibit_line_item_number_Type" minOccurs="0"/>
 *         <element name="protdqty" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}prorated_quantity_Type" minOccurs="0"/>
 *         <element name="qtyprcd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_procured_Type" minOccurs="0"/>
 *         <element name="qtyshpd" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_shipped_Type" minOccurs="0"/>
 *         <element name="rsplisn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replaced_or_superseding_provisioning_list_item_sequence_number_Type" minOccurs="0"/>
 *         <element name="rsplisni" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}replaced_or_superseding_provisioning_list_item_sequence_number_indicator_Type" minOccurs="0"/>
 *         <element name="ttitmcng" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}total_item_changes_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HQ" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HQ_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HR" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HR_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="HX" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}HX_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attribute name="can" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}change_authority_number_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HP_Type", propOrder = {
    "intrcan",
    "prexlino",
    "protdqty",
    "qtyprcd",
    "qtyshpd",
    "rsplisn",
    "rsplisni",
    "ttitmcng",
    "extension",
    "hq",
    "hr",
    "hx"
})
public class HPType {

    /**
     * Interchangeability Code
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected InterchangeabilityCodeType intrcan;
    /**
     * Prorated Exhibit Line Item Number
     * 
     */
    @XmlElement
    protected String prexlino;
    /**
     * Prorated Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer protdqty;
    /**
     * Quantity Procured
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer qtyprcd;
    /**
     * Quantity Shipped
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer qtyshpd;
    /**
     * Replaced Or Superseding Provisioning List Item Sequence Number
     * 
     */
    @XmlElement
    protected String rsplisn;
    /**
     * Replaced Or Superseding Provisioning List Item Sequence Number Indicator
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected ReplacedOrSupersedingProvisioningListItemSequenceNumberIndicatorType rsplisni;
    /**
     * Total Item Changes
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer ttitmcng;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Serial Number Effectivity Data
     * 
     */
    @XmlElement(name = "HQ")
    protected List<HQType> hq;
    /**
     * Design Change Usable On Code Data
     * 
     */
    @XmlElement(name = "HR")
    protected List<HRType> hr;
    /**
     * Design Change Digital File Data
     * 
     */
    @XmlElement(name = "HX")
    protected List<HXType> hx;
    /**
     * Change Authority Number
     * 
     */
    @XmlAttribute(name = "can", required = true)
    protected String can;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Interchangeability Code
     * 
     * @return
     *     possible object is
     *     {@link InterchangeabilityCodeType }
     *     
     */
    public InterchangeabilityCodeType getIntrcan() {
        return intrcan;
    }

    /**
     * Sets the value of the intrcan property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterchangeabilityCodeType }
     *     
     * @see #getIntrcan()
     */
    public void setIntrcan(InterchangeabilityCodeType value) {
        this.intrcan = value;
    }

    /**
     * Prorated Exhibit Line Item Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrexlino() {
        return prexlino;
    }

    /**
     * Sets the value of the prexlino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPrexlino()
     */
    public void setPrexlino(String value) {
        this.prexlino = value;
    }

    /**
     * Prorated Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProtdqty() {
        return protdqty;
    }

    /**
     * Sets the value of the protdqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getProtdqty()
     */
    public void setProtdqty(Integer value) {
        this.protdqty = value;
    }

    /**
     * Quantity Procured
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQtyprcd() {
        return qtyprcd;
    }

    /**
     * Sets the value of the qtyprcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getQtyprcd()
     */
    public void setQtyprcd(Integer value) {
        this.qtyprcd = value;
    }

    /**
     * Quantity Shipped
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQtyshpd() {
        return qtyshpd;
    }

    /**
     * Sets the value of the qtyshpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getQtyshpd()
     */
    public void setQtyshpd(Integer value) {
        this.qtyshpd = value;
    }

    /**
     * Replaced Or Superseding Provisioning List Item Sequence Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsplisn() {
        return rsplisn;
    }

    /**
     * Sets the value of the rsplisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRsplisn()
     */
    public void setRsplisn(String value) {
        this.rsplisn = value;
    }

    /**
     * Replaced Or Superseding Provisioning List Item Sequence Number Indicator
     * 
     * @return
     *     possible object is
     *     {@link ReplacedOrSupersedingProvisioningListItemSequenceNumberIndicatorType }
     *     
     */
    public ReplacedOrSupersedingProvisioningListItemSequenceNumberIndicatorType getRsplisni() {
        return rsplisni;
    }

    /**
     * Sets the value of the rsplisni property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplacedOrSupersedingProvisioningListItemSequenceNumberIndicatorType }
     *     
     * @see #getRsplisni()
     */
    public void setRsplisni(ReplacedOrSupersedingProvisioningListItemSequenceNumberIndicatorType value) {
        this.rsplisni = value;
    }

    /**
     * Total Item Changes
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTtitmcng() {
        return ttitmcng;
    }

    /**
     * Sets the value of the ttitmcng property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTtitmcng()
     */
    public void setTtitmcng(Integer value) {
        this.ttitmcng = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Serial Number Effectivity Data
     * 
     * Gets the value of the hq property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hq property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HQType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hq property.
     */
    public List<HQType> getHQ() {
        if (hq == null) {
            hq = new ArrayList<>();
        }
        return this.hq;
    }

    /**
     * Design Change Usable On Code Data
     * 
     * Gets the value of the hr property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hr property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HRType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hr property.
     */
    public List<HRType> getHR() {
        if (hr == null) {
            hr = new ArrayList<>();
        }
        return this.hr;
    }

    /**
     * Design Change Digital File Data
     * 
     * Gets the value of the hx property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hx property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HXType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hx property.
     */
    public List<HXType> getHX() {
        if (hx == null) {
            hx = new ArrayList<>();
        }
        return this.hx;
    }

    /**
     * Change Authority Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCan() {
        return can;
    }

    /**
     * Sets the value of the can property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCan()
     */
    public void setCan(String value) {
        this.can = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
