//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for interchangeability_code_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="interchangeability_code_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="OW"/>
 *     <enumeration value="OR"/>
 *     <enumeration value="TW"/>
 *     <enumeration value="NI"/>
 *     <enumeration value="NR"/>
 *     <enumeration value="OM"/>
 *     <enumeration value="TM"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "interchangeability_code_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum InterchangeabilityCodeType {

    OW,
    OR,
    TW,
    NI,
    NR,
    OM,
    TM;

    public String value() {
        return name();
    }

    public static InterchangeabilityCodeType fromValue(String v) {
        return valueOf(v);
    }

}
