//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Transport by Fiscal Year Data
 * 
 * <p>Java class for JE_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="JE_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="fiqpqtje" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}procurement_quantity_Type" minOccurs="0"/>
 *         <element name="fqpqtyje" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}procurement_quantity_Type" minOccurs="0"/>
 *         <element name="sqpqtyje" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}procurement_quantity_Type" minOccurs="0"/>
 *         <element name="tqpqtyje" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}procurement_quantity_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attribute name="trfiscyr" use="required" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}fiscal_year_Type" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JE_Type", propOrder = {
    "fiqpqtje",
    "fqpqtyje",
    "sqpqtyje",
    "tqpqtyje",
    "extension"
})
public class JEType {

    /**
     * First Quarter Procurement Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer fiqpqtje;
    /**
     * Fourth Quarter Procurement Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer fqpqtyje;
    /**
     * Second Quarter Procurement Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer sqpqtyje;
    /**
     * Third Quarter Procurement Quantity
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer tqpqtyje;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Transport Fiscal Year
     * 
     */
    @XmlAttribute(name = "trfiscyr", required = true)
    protected XMLGregorianCalendar trfiscyr;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * First Quarter Procurement Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFiqpqtje() {
        return fiqpqtje;
    }

    /**
     * Sets the value of the fiqpqtje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getFiqpqtje()
     */
    public void setFiqpqtje(Integer value) {
        this.fiqpqtje = value;
    }

    /**
     * Fourth Quarter Procurement Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFqpqtyje() {
        return fqpqtyje;
    }

    /**
     * Sets the value of the fqpqtyje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getFqpqtyje()
     */
    public void setFqpqtyje(Integer value) {
        this.fqpqtyje = value;
    }

    /**
     * Second Quarter Procurement Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSqpqtyje() {
        return sqpqtyje;
    }

    /**
     * Sets the value of the sqpqtyje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSqpqtyje()
     */
    public void setSqpqtyje(Integer value) {
        this.sqpqtyje = value;
    }

    /**
     * Third Quarter Procurement Quantity
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTqpqtyje() {
        return tqpqtyje;
    }

    /**
     * Sets the value of the tqpqtyje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTqpqtyje()
     */
    public void setTqpqtyje(Integer value) {
        this.tqpqtyje = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Transport Fiscal Year
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrfiscyr() {
        return trfiscyr;
    }

    /**
     * Sets the value of the trfiscyr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getTrfiscyr()
     */
    public void setTrfiscyr(XMLGregorianCalendar value) {
        this.trfiscyr = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
