//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for measurement_base_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="measurement_base_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="A"/>
 *     <enumeration value="C"/>
 *     <enumeration value="D"/>
 *     <enumeration value="F"/>
 *     <enumeration value="G"/>
 *     <enumeration value="H"/>
 *     <enumeration value="K"/>
 *     <enumeration value="L"/>
 *     <enumeration value="M"/>
 *     <enumeration value="O"/>
 *     <enumeration value="R"/>
 *     <enumeration value="S"/>
 *     <enumeration value="T"/>
 *     <enumeration value="U"/>
 *     <enumeration value="Y"/>
 *     <enumeration value="E"/>
 *     <enumeration value="B"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "measurement_base_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum MeasurementBaseType {

    A,
    C,
    D,
    F,
    G,
    H,
    K,
    L,
    M,
    O,
    R,
    S,
    T,
    U,
    Y,
    E,
    B;

    public String value() {
        return name();
    }

    public static MeasurementBaseType fromValue(String v) {
        return valueOf(v);
    }

}
