//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for objective_state_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="objective_state_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="task_checked"/>
 *     <enumeration value="jacked"/>
 *     <enumeration value="unjacked"/>
 *     <enumeration value="safety_device_established"/>
 *     <enumeration value="electrical_power_established"/>
 *     <enumeration value="electrical_power_from_engine_established"/>
 *     <enumeration value="electrical_power_from_apu_established"/>
 *     <enumeration value="external_electrical_power_established"/>
 *     <enumeration value="internal_electrical_power_established"/>
 *     <enumeration value="hydraulic_power_established"/>
 *     <enumeration value="air_supply_established"/>
 *     <enumeration value="fueled"/>
 *     <enumeration value="defueled"/>
 *     <enumeration value="water_supply_established"/>
 *     <enumeration value="controls_status_established"/>
 *     <enumeration value="controls_status_established"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "objective_state_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum ObjectiveStateType {

    @XmlEnumValue("task_checked")
    TASK_CHECKED("task_checked"),
    @XmlEnumValue("jacked")
    JACKED("jacked"),
    @XmlEnumValue("unjacked")
    UNJACKED("unjacked"),
    @XmlEnumValue("safety_device_established")
    SAFETY_DEVICE_ESTABLISHED("safety_device_established"),
    @XmlEnumValue("electrical_power_established")
    ELECTRICAL_POWER_ESTABLISHED("electrical_power_established"),
    @XmlEnumValue("electrical_power_from_engine_established")
    ELECTRICAL_POWER_FROM_ENGINE_ESTABLISHED("electrical_power_from_engine_established"),
    @XmlEnumValue("electrical_power_from_apu_established")
    ELECTRICAL_POWER_FROM_APU_ESTABLISHED("electrical_power_from_apu_established"),
    @XmlEnumValue("external_electrical_power_established")
    EXTERNAL_ELECTRICAL_POWER_ESTABLISHED("external_electrical_power_established"),
    @XmlEnumValue("internal_electrical_power_established")
    INTERNAL_ELECTRICAL_POWER_ESTABLISHED("internal_electrical_power_established"),
    @XmlEnumValue("hydraulic_power_established")
    HYDRAULIC_POWER_ESTABLISHED("hydraulic_power_established"),
    @XmlEnumValue("air_supply_established")
    AIR_SUPPLY_ESTABLISHED("air_supply_established"),
    @XmlEnumValue("fueled")
    FUELED("fueled"),
    @XmlEnumValue("defueled")
    DEFUELED("defueled"),
    @XmlEnumValue("water_supply_established")
    WATER_SUPPLY_ESTABLISHED("water_supply_established"),
    @XmlEnumValue("controls_status_established")
    CONTROLS_STATUS_ESTABLISHED("controls_status_established");
    private final String value;

    ObjectiveStateType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ObjectiveStateType fromValue(String v) {
        for (ObjectiveStateType c: ObjectiveStateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
