//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for service_designator_code_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="service_designator_code_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="A"/>
 *     <enumeration value="F"/>
 *     <enumeration value="Y"/>
 *     <enumeration value="T"/>
 *     <enumeration value="S"/>
 *     <enumeration value="N"/>
 *     <enumeration value="M"/>
 *     <enumeration value="X"/>
 *     <enumeration value="J"/>
 *     <enumeration value="O"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "service_designator_code_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum ServiceDesignatorCodeType {

    A,
    F,
    Y,
    T,
    S,
    N,
    M,
    X,
    J,
    O;

    public String value() {
        return name();
    }

    public static ServiceDesignatorCodeType fromValue(String v) {
        return valueOf(v);
    }

}
