//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for shipping_configuration_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="shipping_configuration_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CB"/>
 *     <enumeration value="CM"/>
 *     <enumeration value="CN"/>
 *     <enumeration value="CR"/>
 *     <enumeration value="CS"/>
 *     <enumeration value="CT"/>
 *     <enumeration value="CU"/>
 *     <enumeration value="CY"/>
 *     <enumeration value="DR"/>
 *     <enumeration value="EC"/>
 *     <enumeration value="ED"/>
 *     <enumeration value="KE"/>
 *     <enumeration value="LS"/>
 *     <enumeration value="MW"/>
 *     <enumeration value="MX"/>
 *     <enumeration value="PT"/>
 *     <enumeration value="EL"/>
 *     <enumeration value="RT"/>
 *     <enumeration value="SB"/>
 *     <enumeration value="SD"/>
 *     <enumeration value="VE"/>
 *     <enumeration value="VO"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "shipping_configuration_Type", namespace = "http://www.sae.org/geia_std_0007/2018/RevC/types")
@XmlEnum
public enum ShippingConfigurationType {

    CB,
    CM,
    CN,
    CR,
    CS,
    CT,
    CU,
    CY,
    DR,
    EC,
    ED,
    KE,
    LS,
    MW,
    MX,
    PT,
    EL,
    RT,
    SB,
    SD,
    VE,
    VO;

    public String value() {
        return name();
    }

    public static ShippingConfigurationType fromValue(String v) {
        return valueOf(v);
    }

}
