//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Operational Test Program Data
 * 
 * <p>Java class for UC_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="UC_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="otpaucnr" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_cost_Type" minOccurs="0"/>
 *         <element name="otpaucnc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}currency_code_Type" minOccurs="0"/>
 *         <element name="otpaucr" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}unit_cost_Type" minOccurs="0"/>
 *         <element name="otpctp" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operational_test_program_coordinated_test_plan_Type" minOccurs="0"/>
 *         <element name="otpstdcp" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}operational_test_program_standards_for_comparison_Type" minOccurs="0"/>
 *         <element name="serdatno" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}support_equipment_recommendation_data_number_Type" minOccurs="0"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="UE" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}UE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UC_Type", propOrder = {
    "otpaucnr",
    "otpaucnc",
    "otpaucr",
    "otpctp",
    "otpstdcp",
    "serdatno",
    "extension",
    "ue"
})
public class UCType {

    /**
     * Operational Test Program Apportioned Unit Cost Nonrecurring
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer otpaucnr;
    /**
     * Operational Test Program Apportioned Unit Cost Nonrecurring Recurring Currency Code
     * 
     */
    @XmlElement
    protected String otpaucnc;
    /**
     * Operational Test Program Apportioned Unit Cost Recurring
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer otpaucr;
    /**
     * Operational Test Program Coordinated Test Plan
     * 
     */
    @XmlElement
    protected Boolean otpctp;
    /**
     * Operational Test Program Standards For Comparison
     * 
     */
    @XmlElement
    protected Boolean otpstdcp;
    /**
     * Operational Test Program Support Equipment Recommendation Data Number
     * 
     */
    @XmlElement
    protected String serdatno;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * Test Program Instruction Data
     * 
     */
    @XmlElement(name = "UE")
    protected List<UEType> ue;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;

    /**
     * Operational Test Program Apportioned Unit Cost Nonrecurring
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOtpaucnr() {
        return otpaucnr;
    }

    /**
     * Sets the value of the otpaucnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOtpaucnr()
     */
    public void setOtpaucnr(Integer value) {
        this.otpaucnr = value;
    }

    /**
     * Operational Test Program Apportioned Unit Cost Nonrecurring Recurring Currency Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtpaucnc() {
        return otpaucnc;
    }

    /**
     * Sets the value of the otpaucnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOtpaucnc()
     */
    public void setOtpaucnc(String value) {
        this.otpaucnc = value;
    }

    /**
     * Operational Test Program Apportioned Unit Cost Recurring
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOtpaucr() {
        return otpaucr;
    }

    /**
     * Sets the value of the otpaucr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOtpaucr()
     */
    public void setOtpaucr(Integer value) {
        this.otpaucr = value;
    }

    /**
     * Operational Test Program Coordinated Test Plan
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getOtpctp() {
        return otpctp;
    }

    /**
     * Sets the value of the otpctp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getOtpctp()
     */
    public void setOtpctp(Boolean value) {
        this.otpctp = value;
    }

    /**
     * Operational Test Program Standards For Comparison
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getOtpstdcp() {
        return otpstdcp;
    }

    /**
     * Sets the value of the otpstdcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getOtpstdcp()
     */
    public void setOtpstdcp(Boolean value) {
        this.otpstdcp = value;
    }

    /**
     * Operational Test Program Support Equipment Recommendation Data Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerdatno() {
        return serdatno;
    }

    /**
     * Sets the value of the serdatno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSerdatno()
     */
    public void setSerdatno(String value) {
        this.serdatno = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Test Program Instruction Data
     * 
     * Gets the value of the ue property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ue property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getUE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UEType }
     * </p>
     * 
     * 
     * @return
     *     The value of the ue property.
     */
    public List<UEType> getUE() {
        if (ue == null) {
            ue = new ArrayList<>();
        }
        return this.ue;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

}
