//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.clanmchperson.geia0007c;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * System End Item Data
 * 
 * <p>Java class for XC_Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="XC_Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="qoeicoc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_end_item_calculation_option_code_Type" minOccurs="0"/>
 *         <element name="seidesc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}item_designator_code_Type" minOccurs="0"/>
 *         <element name="seipccn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_contract_control_number_Type"/>
 *         <element name="seiplisn" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}provisioning_list_item_sequence_number_Type" minOccurs="0"/>
 *         <element name="seiqpa" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_assembly_Type" minOccurs="0"/>
 *         <element name="seiqpei" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}quantity_per_end_item_Type" minOccurs="0"/>
 *         <element name="seityocc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}type_of_change_code_Type" minOccurs="0"/>
 *         <element name="traneiin" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}transportation_end_item_indicator_Type" minOccurs="0"/>
 *         <element name="uoc" type="{http://www.sae.org/geia_std_0007/2018/RevC/types}usable_on_code_Type"/>
 *         <element ref="{http://www.sae.org/geia_std_0007/2018/RevC/schema}extension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="XD" type="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}XD_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}change_attribute_group"/>
 *       <attGroup ref="{http://www.sae.org/geia_std_0007/2018/RevC/lpd}entity_attribute_group"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XC_Type", propOrder = {
    "qoeicoc",
    "seidesc",
    "seipccn",
    "seiplisn",
    "seiqpa",
    "seiqpei",
    "seityocc",
    "traneiin",
    "uoc",
    "extension",
    "xd"
})
public class XCType {

    /**
     * Quantity Per End Item Calculation Option Code
     * 
     */
    @XmlElement
    protected BigInteger qoeicoc;
    /**
     * System End Item Item Designator Code
     * 
     */
    @XmlElement
    protected String seidesc;
    /**
     * System End Item Provisioning Contract Control Number
     * 
     */
    @XmlElement(required = true, nillable = true)
    protected String seipccn;
    /**
     * System End Item Provisioning List Item Sequence Number
     * 
     */
    @XmlElement
    protected String seiplisn;
    /**
     * System End Item Quantity Per Assembly
     * 
     */
    @XmlElement
    protected String seiqpa;
    /**
     * System End Item Quantity Per End Item
     * 
     */
    @XmlElement
    protected String seiqpei;
    /**
     * System End Item Type Of Change Code
     * 
     */
    @XmlElement
    @XmlSchemaType(name = "string")
    protected TypeOfChangeCodeType seityocc;
    /**
     * Transportation End Item Indicator
     * 
     */
    @XmlElement
    protected Boolean traneiin;
    /**
     * Usable On Code
     * 
     */
    @XmlElement(required = true, nillable = true)
    protected String uoc;
    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     */
    @XmlElement(namespace = "http://www.sae.org/geia_std_0007/2018/RevC/schema")
    protected List<Extension> extension;
    /**
     * System End Item Serial Number Data
     * 
     */
    @XmlElement(name = "XD")
    protected List<XDType> xd;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "change_to")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object changeTo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Quantity Per End Item Calculation Option Code
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQoeicoc() {
        return qoeicoc;
    }

    /**
     * Sets the value of the qoeicoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getQoeicoc()
     */
    public void setQoeicoc(BigInteger value) {
        this.qoeicoc = value;
    }

    /**
     * System End Item Item Designator Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeidesc() {
        return seidesc;
    }

    /**
     * Sets the value of the seidesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSeidesc()
     */
    public void setSeidesc(String value) {
        this.seidesc = value;
    }

    /**
     * System End Item Provisioning Contract Control Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeipccn() {
        return seipccn;
    }

    /**
     * Sets the value of the seipccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSeipccn()
     */
    public void setSeipccn(String value) {
        this.seipccn = value;
    }

    /**
     * System End Item Provisioning List Item Sequence Number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeiplisn() {
        return seiplisn;
    }

    /**
     * Sets the value of the seiplisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSeiplisn()
     */
    public void setSeiplisn(String value) {
        this.seiplisn = value;
    }

    /**
     * System End Item Quantity Per Assembly
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeiqpa() {
        return seiqpa;
    }

    /**
     * Sets the value of the seiqpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSeiqpa()
     */
    public void setSeiqpa(String value) {
        this.seiqpa = value;
    }

    /**
     * System End Item Quantity Per End Item
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeiqpei() {
        return seiqpei;
    }

    /**
     * Sets the value of the seiqpei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSeiqpei()
     */
    public void setSeiqpei(String value) {
        this.seiqpei = value;
    }

    /**
     * System End Item Type Of Change Code
     * 
     * @return
     *     possible object is
     *     {@link TypeOfChangeCodeType }
     *     
     */
    public TypeOfChangeCodeType getSeityocc() {
        return seityocc;
    }

    /**
     * Sets the value of the seityocc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfChangeCodeType }
     *     
     * @see #getSeityocc()
     */
    public void setSeityocc(TypeOfChangeCodeType value) {
        this.seityocc = value;
    }

    /**
     * Transportation End Item Indicator
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTraneiin() {
        return traneiin;
    }

    /**
     * Sets the value of the traneiin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #getTraneiin()
     */
    public void setTraneiin(Boolean value) {
        this.traneiin = value;
    }

    /**
     * Usable On Code
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUoc() {
        return uoc;
    }

    /**
     * Sets the value of the uoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUoc()
     */
    public void setUoc(String value) {
        this.uoc = value;
    }

    /**
     * This element allows for the exchange of user defined data such as project, organization, and/or country specific data. These data must be agreed upon and defined by trading partners and coordinated with LPD software products as applicable for each particular project need.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * System End Item Serial Number Data
     * 
     * Gets the value of the xd property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xd property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getXD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XDType }
     * </p>
     * 
     * 
     * @return
     *     The value of the xd property.
     */
    public List<XDType> getXD() {
        if (xd == null) {
            xd = new ArrayList<>();
        }
        return this.xd;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the changeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChangeTo() {
        return changeTo;
    }

    /**
     * Sets the value of the changeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChangeTo(Object value) {
        this.changeTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
